//
// TraitListResponseResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BrAPITraitListResponseResult: Codable {

    public var data: [BrAPITrait]

    public init(data: [BrAPITrait]) {
        self.data = data
    }


}
