//
// ObservationUnitNewRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BrAPIObservationUnitNewRequest: Codable {

    /** Additional arbitrary info */
    public var additionalInfo: [String:String]?
    /** An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI. */
    public var externalReferences: [BrAPIExternalReferencesInner]?
    /** The ID which uniquely identifies a germplasm */
    public var germplasmDbId: String?
    /** Name of the germplasm. It can be the preferred name and does not have to be unique. */
    public var germplasmName: String?
    /** The ID which uniquely identifies a location, associated with this study */
    public var locationDbId: String?
    /** The human readable name of a location associated with this study */
    public var locationName: String?
    /** A human readable name for an observation unit */
    public var observationUnitName: String?
    /** A Permanent Unique Identifier for an observation unit  MIAPPE V1.1 (DM-72) External ID - Identifier for the observation unit in a persistent repository, comprises the name of the repository and the identifier of the observation unit therein. The EBI Biosamples repository can be used. URI are recommended when possible. */
    public var observationUnitPUI: String?
    public var observationUnitPosition: BrAPIObservationUnitPosition?
    /** The ID which uniquely identifies a program */
    public var programDbId: String?
    /** The human readable name of a program */
    public var programName: String?
    /** The unique identifier for the originating Seed Lot */
    public var seedLotDbId: String?
    /** The ID which uniquely identifies a study within the given database server */
    public var studyDbId: String?
    /** The human readable name for a study */
    public var studyName: String?
    /** List of treatments applied to an observation unit.  MIAPPE V1.1 (DM-74) Observation Unit factor value - List of values for each factor applied to the observation unit. */
    public var treatments: [BrAPITreatment]?
    /** The ID which uniquely identifies a trial */
    public var trialDbId: String?
    /** The human readable name of a trial */
    public var trialName: String?

    public init(additionalInfo: [String:String]? = nil, externalReferences: [BrAPIExternalReferencesInner]? = nil, germplasmDbId: String? = nil, germplasmName: String? = nil, locationDbId: String? = nil, locationName: String? = nil, observationUnitName: String? = nil, observationUnitPUI: String? = nil, observationUnitPosition: BrAPIObservationUnitPosition? = nil, programDbId: String? = nil, programName: String? = nil, seedLotDbId: String? = nil, studyDbId: String? = nil, studyName: String? = nil, treatments: [BrAPITreatment]? = nil, trialDbId: String? = nil, trialName: String? = nil) {
        self.additionalInfo = additionalInfo
        self.externalReferences = externalReferences
        self.germplasmDbId = germplasmDbId
        self.germplasmName = germplasmName
        self.locationDbId = locationDbId
        self.locationName = locationName
        self.observationUnitName = observationUnitName
        self.observationUnitPUI = observationUnitPUI
        self.observationUnitPosition = observationUnitPosition
        self.programDbId = programDbId
        self.programName = programName
        self.seedLotDbId = seedLotDbId
        self.studyDbId = studyDbId
        self.studyName = studyName
        self.treatments = treatments
        self.trialDbId = trialDbId
        self.trialName = trialName
    }


}
