//
// ObservationUnitSingleResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BrAPIObservationUnitSingleResponse: Codable {

    public var context: BrAPIContext?
    public var metadata: BrAPIMetadata
    public var result: BrAPIObservationUnit

    public init(context: BrAPIContext? = nil, metadata: BrAPIMetadata, result: BrAPIObservationUnit) {
        self.context = context
        self.metadata = metadata
        self.result = result
    }

    public enum CodingKeys: String, CodingKey { 
        case context = "@context"
        case metadata
        case result
    }

}
