//
// SeasonListResponseResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BrAPISeasonListResponseResult: Codable {

    public var data: [BrAPISeason]

    public init(data: [BrAPISeason]) {
        self.data = data
    }


}
