//
// Contact.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Contact: Codable {

    /** The ID which uniquely identifies this contact  MIAPPE V1.1 (DM-33) Person ID - An identifier for the data submitter. If that submitter is an individual, ORCID identifiers are recommended. */
    public var contactDbId: String
    /** The contacts email address  MIAPPE V1.1 (DM-32) Person email - The electronic mail address of the person. */
    public var email: String?
    /** The name of the institution which this contact is part of  MIAPPE V1.1 (DM-35) Person affiliation - The institution the person belongs to */
    public var instituteName: String?
    /** The full name of this contact person  MIAPPE V1.1 (DM-31) Person name - The name of the person (either full name or as used in scientific publications) */
    public var name: String?
    /** The Open Researcher and Contributor ID for this contact person (orcid.org)  MIAPPE V1.1 (DM-33) Person ID - An identifier for the data submitter. If that submitter is an individual, ORCID identifiers are recommended. */
    public var orcid: String?
    /** The type of person this contact represents (ex: Coordinator, Scientist, PI, etc.)  MIAPPE V1.1 (DM-34) Person role - Type of contribution of the person to the investigation */
    public var type: String?

    public init(contactDbId: String, email: String? = nil, instituteName: String? = nil, name: String? = nil, orcid: String? = nil, type: String? = nil) {
        self.contactDbId = contactDbId
        self.email = email
        self.instituteName = instituteName
        self.name = name
        self.orcid = orcid
        self.type = type
    }


}
