//
// Polygon.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An array of linear rings */
public typealias Polygon = [Array<Any>]
