//
// PersonListResponseResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BrAPIPersonListResponseResult: Codable {

    /** Array of people */
    public var data: [BrAPIPerson]

    public init(data: [BrAPIPerson]) {
        self.data = data
    }


}
