//
// StudyTypesResponseResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BrAPIStudyTypesResponseResult: Codable {

    /** the list of all study types available in this server. */
    public var data: [String]

    public init(data: [String]) {
        self.data = data
    }


}
