//
// ScaleListResponseResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ScaleListResponseResult: Codable {

    public var data: [Scale]

    public init(data: [Scale]) {
        self.data = data
    }


}
