//
// ObservationLevelListResponseResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ObservationLevelListResponseResult: Codable {

    public var data: [ObservationUnitHierarchyLevel]

    public init(data: [ObservationUnitHierarchyLevel]) {
        self.data = data
    }


}
