//
// ObservationListResponseResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ObservationListResponseResult: Codable {

    public var data: [Observation]

    public init(data: [Observation]) {
        self.data = data
    }


}
