//
// ObservationUnitPosition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** All positional and layout information related to this Observation Unit  MIAPPE V1.1 (DM-73) Spatial distribution - Type and value of a spatial coordinate (georeference or relative) or level of observation (plot 45, subblock 7, block 2) provided as a key-value pair of the form type:value. Levels of observation must be consistent with those listed in the Study section. */

public struct ObservationUnitPosition: Codable {

    public enum EntryType: String, Codable { 
        case check = "CHECK"
        case test = "TEST"
        case filler = "FILLER"
    }
    public enum PositionCoordinateXType: String, Codable { 
        case longitude = "LONGITUDE"
        case latitude = "LATITUDE"
        case plantedRow = "PLANTED_ROW"
        case plantedIndividual = "PLANTED_INDIVIDUAL"
        case gridRow = "GRID_ROW"
        case gridCol = "GRID_COL"
        case measuredRow = "MEASURED_ROW"
        case measuredCol = "MEASURED_COL"
    }
    public enum PositionCoordinateYType: String, Codable { 
        case longitude = "LONGITUDE"
        case latitude = "LATITUDE"
        case plantedRow = "PLANTED_ROW"
        case plantedIndividual = "PLANTED_INDIVIDUAL"
        case gridRow = "GRID_ROW"
        case gridCol = "GRID_COL"
        case measuredRow = "MEASURED_ROW"
        case measuredCol = "MEASURED_COL"
    }
    /** The type of entry for this observation unit. ex. \&quot;CHECK\&quot;, \&quot;TEST\&quot;, \&quot;FILLER\&quot; */
    public var entryType: EntryType?
    public var geoCoordinates: GeoJSON?
    public var observationLevel: ObservationUnitHierarchyLevel?
    /** Observation levels indicate the granularity level at which the measurements are taken.     For more information on Observation Levels, please review the &lt;a target&#x3D;\&quot;_blank\&quot; href&#x3D;\&quot;https://wiki.brapi.org/index.php/Observation_Levels\&quot;&gt;Observation Levels documentation&lt;/a&gt;.  &#x60;levelName&#x60; defines the level   &#x60;levelOrder&#x60; defines where that level exists in the hierarchy of levels. &#x60;levelOrder&#x60;s lower numbers are at the top of the hierarchy (ie field &gt; 0) and higher numbers are at the bottom of the hierarchy (ie plant &gt; 6).   &#x60;levelCode&#x60; is an ID code for this level tag. Identify this observation unit by each level of the hierarchy where it exists */
    public var observationLevelRelationships: [ObservationUnitHierarchyLevel]?
    /** The X position coordinate for an observation unit. Different systems may use different coordinate systems. */
    public var positionCoordinateX: String?
    /** The type of positional coordinate used. Must be one of the following values  LONGITUDE - ISO 6709 standard, WGS84 geodetic datum. See &#x27;Location Coordinate Encoding&#x27; for details  LATITUDE - ISO 6709 standard, WGS84 geodetic datum. See &#x27;Location Coordinate Encoding&#x27; for details  PLANTED_ROW - The physical planted row number   PLANTED_INDIVIDUAL - The physical counted number, could be independant or within a planted row  GRID_ROW - The row index number of a square grid overlay  GRID_COL - The column index number of a square grid overlay  MEASURED_ROW - The distance in meters from a defined 0-th row  MEASURED_COL - The distance in meters from a defined 0-th column */
    public var positionCoordinateXType: PositionCoordinateXType?
    /** The Y position coordinate for an observation unit. Different systems may use different coordinate systems. */
    public var positionCoordinateY: String?
    /** The type of positional coordinate used. Must be one of the following values  LONGITUDE - ISO 6709 standard, WGS84 geodetic datum. See &#x27;Location Coordinate Encoding&#x27; for details  LATITUDE - ISO 6709 standard, WGS84 geodetic datum. See &#x27;Location Coordinate Encoding&#x27; for details  PLANTED_ROW - The physical planted row number   PLANTED_INDIVIDUAL - The physical counted number, could be independant or within a planted row  GRID_ROW - The row index number of a square grid overlay  GRID_COL - The column index number of a square grid overlay  MEASURED_ROW - The distance in meters from a defined 0-th row  MEASURED_COL - The distance in meters from a defined 0-th column */
    public var positionCoordinateYType: PositionCoordinateYType?

    public init(entryType: EntryType? = nil, geoCoordinates: GeoJSON? = nil, observationLevel: ObservationUnitHierarchyLevel? = nil, observationLevelRelationships: [ObservationUnitHierarchyLevel]? = nil, positionCoordinateX: String? = nil, positionCoordinateXType: PositionCoordinateXType? = nil, positionCoordinateY: String? = nil, positionCoordinateYType: PositionCoordinateYType? = nil) {
        self.entryType = entryType
        self.geoCoordinates = geoCoordinates
        self.observationLevel = observationLevel
        self.observationLevelRelationships = observationLevelRelationships
        self.positionCoordinateX = positionCoordinateX
        self.positionCoordinateXType = positionCoordinateXType
        self.positionCoordinateY = positionCoordinateY
        self.positionCoordinateYType = positionCoordinateYType
    }


}
