//
// OntologyListResponseResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OntologyListResponseResult: Codable {

    public var data: [Ontology]

    public init(data: [Ontology]) {
        self.data = data
    }


}
