//
// CommonCropNamesResponseResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BrAPICommonCropNamesResponseResult: Codable {

    /** array of crop names available on the server */
    public var data: [String]

    public init(data: [String]) {
        self.data = data
    }


}
