//
// ImageListResponseResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ImageListResponseResult: Codable {

    /** Array of image meta data */
    public var data: [Image]

    public init(data: [Image]) {
        self.data = data
    }


}
