//
// Service.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Service: Codable {

    public enum Methods: String, Codable { 
        case _get = "GET"
        case post = "POST"
        case put = "PUT"
        case delete = "DELETE"
    }
    public enum Versions: String, Codable { 
        case _0 = "2.0"
        case _1 = "2.1"
        case _2 = "2.2"
    }
    /** The possible data formats returned by the available call */
    public var dataTypes: [WSMIMEDataTypes]?
    /** The possible HTTP Methods to be used with the available call */
    public var methods: [Methods]
    /** The name of the available call as recorded in the documentation */
    public var service: String
    /** The supported versions of a particular call */
    public var versions: [Versions]

    public init(dataTypes: [WSMIMEDataTypes]? = nil, methods: [Methods], service: String, versions: [Versions]) {
        self.dataTypes = dataTypes
        self.methods = methods
        self.service = service
        self.versions = versions
    }


}
