//
// Event.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Event: Codable {

    /** Additional arbitrary info */
    public var additionalInfo: [String:String]?
    /** A list of dates when the event occurred  MIAPPE V1.1 (DM-68) Event date - Date and time of the event. */
    public var date: [Date]?
    /** Internal database identifier */
    public var eventDbId: String
    /** A detailed, human-readable description of this event  MIAPPE V1.1 (DM-67) Event description - Description of the event, including details such as amount applied and possibly duration of the event.  */
    public var eventDescription: String?
    /** A list of objects describing additional event parameters. Each of the following accepts a human-readable value or URI */
    public var eventParameters: [EventEventParameters]?
    /** General category for this event (e.g. Sowing, Watering, Rain). Each eventType should correspond to exactly one eventTypeDbId, if provided.  MIAPPE V1.1 (DM-65) Event type - Short name of the event. */
    public var eventType: String
    /** An identifier for this event type, in the form of an ontology class reference  MIAPPE V1.1 (DM-66) Event accession number - Accession number of the event type in a suitable controlled vocabulary (Crop Ontology). */
    public var eventTypeDbId: String?
    /** A list of the affected observation units. If this parameter is not given, it is understood that the event affected all units in the study */
    public var observationUnitDbIds: [String]?
    /** The study in which the event occurred */
    public var studyDbId: String?

    public init(additionalInfo: [String:String]? = nil, date: [Date]? = nil, eventDbId: String, eventDescription: String? = nil, eventParameters: [EventEventParameters]? = nil, eventType: String, eventTypeDbId: String? = nil, observationUnitDbIds: [String]? = nil, studyDbId: String? = nil) {
        self.additionalInfo = additionalInfo
        self.date = date
        self.eventDbId = eventDbId
        self.eventDescription = eventDescription
        self.eventParameters = eventParameters
        self.eventType = eventType
        self.eventTypeDbId = eventTypeDbId
        self.observationUnitDbIds = observationUnitDbIds
        self.studyDbId = studyDbId
    }


}
