//
// Model202AcceptedSearchResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Model202AcceptedSearchResponse: Codable {

    public var context: Context?
    public var metadata: Metadata?
    public var result: Model202AcceptedSearchResponseResult?

    public init(context: Context? = nil, metadata: Metadata? = nil, result: Model202AcceptedSearchResponseResult? = nil) {
        self.context = context
        self.metadata = metadata
        self.result = result
    }

    public enum CodingKeys: String, CodingKey { 
        case context = "@context"
        case metadata
        case result
    }

}
