//
// SearchRequestParametersGermplasm.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchRequestParametersGermplasm: Codable {

    /** List of IDs which uniquely identify germplasm to search for */
    public var germplasmDbIds: [String]?
    /** List of human readable names to identify germplasm to search for */
    public var germplasmNames: [String]?

    public init(germplasmDbIds: [String]? = nil, germplasmNames: [String]? = nil) {
        self.germplasmDbIds = germplasmDbIds
        self.germplasmNames = germplasmNames
    }


}
