//
// ObservationUnitsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class ObservationUnitsAPI {
    /**
     Get the Observation Levels

     - parameter studyDbId: (query) Filter by study DbId (optional)
     - parameter trialDbId: (query) Filter by trial DbId (optional)
     - parameter programDbId: (query) Filter by program DbId (optional)
     - parameter page: (query) Used to request a specific page of data to be returned.  The page indexing starts at 0 (the first page is &#x27;page&#x27;&#x3D; 0). Default is &#x60;0&#x60;. (optional)
     - parameter pageSize: (query) The size of the pages to be returned. Default is &#x60;1000&#x60;. (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func observationlevelsGet(studyDbId: String? = nil, trialDbId: String? = nil, programDbId: String? = nil, page: Int? = nil, pageSize: Int? = nil, authorization: String? = nil, completion: @escaping ((_ data: ObservationLevelListResponse?,_ error: Error?) -> Void)) {
        observationlevelsGetWithRequestBuilder(studyDbId: studyDbId, trialDbId: trialDbId, programDbId: programDbId, page: page, pageSize: pageSize, authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get the Observation Levels
     - GET /observationlevels

     - :
       - type: http
       - name: AuthorizationToken
     - examples: [{contentType=application/json, example={
  "result" : {
    "data" : [ {
      "levelName" : "field",
      "levelOrder" : 0
    }, {
      "levelName" : "block",
      "levelOrder" : 1
    }, {
      "levelName" : "plot",
      "levelOrder" : 2
    }, {
      "levelName" : "sub-plot",
      "levelOrder" : 3
    }, {
      "levelName" : "plant",
      "levelOrder" : 4
    } ]
  },
  "metadata" : {
    "pagination" : {
      "totalPages" : 1,
      "pageSize" : 1000,
      "currentPage" : 0,
      "totalCount" : 10
    },
    "datafiles" : [ {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    }, {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    } ],
    "status" : [ {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    }, {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    } ]
  },
  "@context" : [ "https://brapi.org/jsonld/context/metadata.jsonld" ]
}}]
     - parameter studyDbId: (query) Filter by study DbId (optional)
     - parameter trialDbId: (query) Filter by trial DbId (optional)
     - parameter programDbId: (query) Filter by program DbId (optional)
     - parameter page: (query) Used to request a specific page of data to be returned.  The page indexing starts at 0 (the first page is &#x27;page&#x27;&#x3D; 0). Default is &#x60;0&#x60;. (optional)
     - parameter pageSize: (query) The size of the pages to be returned. Default is &#x60;1000&#x60;. (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)

     - returns: RequestBuilder<ObservationLevelListResponse> 
     */
    open class func observationlevelsGetWithRequestBuilder(studyDbId: String? = nil, trialDbId: String? = nil, programDbId: String? = nil, page: Int? = nil, pageSize: Int? = nil, authorization: String? = nil) -> RequestBuilder<ObservationLevelListResponse> {
        let path = "/observationlevels"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "studyDbId": studyDbId, 
                        "trialDbId": trialDbId, 
                        "programDbId": programDbId, 
                        "page": page?.encodeToJSON(), 
                        "pageSize": pageSize?.encodeToJSON()
        ])
        let nillableHeaders: [String: Any?] = [
                        "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ObservationLevelListResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     Get a filtered set of Observation Units

     - parameter observationUnitDbId: (query) The unique ID of an Observation Unit (optional)
     - parameter germplasmDbId: (query) The unique ID of a germplasm (accession) to filter on (optional)
     - parameter studyDbId: (query) The unique ID of a studies to filter on (optional)
     - parameter locationDbId: (query) The unique ID of a location where these observations were collected (optional)
     - parameter trialDbId: (query) The unique ID of a trial to filter on (optional)
     - parameter programDbId: (query) The unique ID of a program to filter on (optional)
     - parameter seasonDbId: (query) The year or Phenotyping campaign of a multi-annual study (trees, grape, ...) (optional)
     - parameter observationUnitLevelName: (query) The Observation Unit Level. Returns only the observation unit of the specified Level. References ObservationUnit-&gt;observationUnitPosition-&gt;observationLevel-&gt;levelName (optional)
     - parameter observationUnitLevelOrder: (query) The Observation Unit Level Order Number. Returns only the observation unit of the specified Level. References ObservationUnit-&gt;observationUnitPosition-&gt;observationLevel-&gt;levelOrder (optional)
     - parameter observationUnitLevelCode: (query) The Observation Unit Level Code. This parameter should be used together with &#x60;observationUnitLevelName&#x60; or &#x60;observationUnitLevelOrder&#x60;. References ObservationUnit-&gt;observationUnitPosition-&gt;observationLevel-&gt;levelCode (optional)
     - parameter includeObservations: (query) Use this parameter to include a list of observations embedded in each ObservationUnit object.   CAUTION - Use this parameter at your own risk. It may return large, unpaginated lists of observation data. Only set this value to True if you are sure you need to. (optional)
     - parameter externalReferenceID: (query) An external reference ID. Could be a simple string or a URI. (use with &#x60;externalReferenceSource&#x60; parameter) (optional)
     - parameter externalReferenceSource: (query) An identifier for the source system or database of an external reference (use with &#x60;externalReferenceID&#x60; parameter) (optional)
     - parameter page: (query) Used to request a specific page of data to be returned.  The page indexing starts at 0 (the first page is &#x27;page&#x27;&#x3D; 0). Default is &#x60;0&#x60;. (optional)
     - parameter pageSize: (query) The size of the pages to be returned. Default is &#x60;1000&#x60;. (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func observationunitsGet(observationUnitDbId: String? = nil, germplasmDbId: String? = nil, studyDbId: String? = nil, locationDbId: String? = nil, trialDbId: String? = nil, programDbId: String? = nil, seasonDbId: String? = nil, observationUnitLevelName: String? = nil, observationUnitLevelOrder: String? = nil, observationUnitLevelCode: String? = nil, includeObservations: Bool? = nil, externalReferenceID: String? = nil, externalReferenceSource: String? = nil, page: Int? = nil, pageSize: Int? = nil, authorization: String? = nil, completion: @escaping ((_ data: ObservationUnitListResponse?,_ error: Error?) -> Void)) {
        observationunitsGetWithRequestBuilder(observationUnitDbId: observationUnitDbId, germplasmDbId: germplasmDbId, studyDbId: studyDbId, locationDbId: locationDbId, trialDbId: trialDbId, programDbId: programDbId, seasonDbId: seasonDbId, observationUnitLevelName: observationUnitLevelName, observationUnitLevelOrder: observationUnitLevelOrder, observationUnitLevelCode: observationUnitLevelCode, includeObservations: includeObservations, externalReferenceID: externalReferenceID, externalReferenceSource: externalReferenceSource, page: page, pageSize: pageSize, authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get a filtered set of Observation Units
     - GET /observationunits

     - :
       - type: http
       - name: AuthorizationToken
     - examples: [{contentType=application/json, example={
  "result" : {
    "data" : [ {
      "observationUnitName" : "Plot 1",
      "trialDbId" : "776a609c",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "observationUnitPosition" : {
        "entryType" : "TEST",
        "positionCoordinateYType" : "GRID_ROW",
        "positionCoordinateX" : "74",
        "positionCoordinateXType" : "GRID_COL",
        "observationLevel" : {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        },
        "observationLevelRelationships" : [ {
          "levelCode" : "Field_1",
          "levelName" : "field",
          "levelOrder" : 0
        }, {
          "levelCode" : "Block_12",
          "levelName" : "block",
          "levelOrder" : 1
        }, {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        } ],
        "geoCoordinates" : {
          "geometry" : {
            "coordinates" : [ -76.506042, 42.417373, 123 ],
            "type" : "Point"
          },
          "type" : "Feature"
        },
        "positionCoordinateY" : "03"
      },
      "locationName" : "Field Station Alpha",
      "studyName" : "Purple_Tomato_1",
      "seedLotDbId" : "261ecb09",
      "germplasmName" : "A0000001",
      "programDbId" : "2d763a7a",
      "germplasmDbId" : "e9d9ed57",
      "treatments" : [ {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      }, {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      } ],
      "studyDbId" : "9865addc",
      "locationDbId" : "0e208b20",
      "trialName" : "Purple Tomato",
      "programName" : "The Perfect Breeding Program",
      "observations" : [ {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      }, {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      } ],
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "observationUnitDbId" : "8c67503c",
      "observationUnitPUI" : "http://pui.per/plot/1a9afc14"
    }, {
      "observationUnitName" : "Plot 1",
      "trialDbId" : "776a609c",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "observationUnitPosition" : {
        "entryType" : "TEST",
        "positionCoordinateYType" : "GRID_ROW",
        "positionCoordinateX" : "74",
        "positionCoordinateXType" : "GRID_COL",
        "observationLevel" : {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        },
        "observationLevelRelationships" : [ {
          "levelCode" : "Field_1",
          "levelName" : "field",
          "levelOrder" : 0
        }, {
          "levelCode" : "Block_12",
          "levelName" : "block",
          "levelOrder" : 1
        }, {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        } ],
        "geoCoordinates" : {
          "geometry" : {
            "coordinates" : [ -76.506042, 42.417373, 123 ],
            "type" : "Point"
          },
          "type" : "Feature"
        },
        "positionCoordinateY" : "03"
      },
      "locationName" : "Field Station Alpha",
      "studyName" : "Purple_Tomato_1",
      "seedLotDbId" : "261ecb09",
      "germplasmName" : "A0000001",
      "programDbId" : "2d763a7a",
      "germplasmDbId" : "e9d9ed57",
      "treatments" : [ {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      }, {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      } ],
      "studyDbId" : "9865addc",
      "locationDbId" : "0e208b20",
      "trialName" : "Purple Tomato",
      "programName" : "The Perfect Breeding Program",
      "observations" : [ {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      }, {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      } ],
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "observationUnitDbId" : "8c67503c",
      "observationUnitPUI" : "http://pui.per/plot/1a9afc14"
    } ]
  },
  "metadata" : {
    "pagination" : {
      "totalPages" : 1,
      "pageSize" : 1000,
      "currentPage" : 0,
      "totalCount" : 10
    },
    "datafiles" : [ {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    }, {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    } ],
    "status" : [ {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    }, {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    } ]
  },
  "@context" : [ "https://brapi.org/jsonld/context/metadata.jsonld" ]
}}]
     - parameter observationUnitDbId: (query) The unique ID of an Observation Unit (optional)
     - parameter germplasmDbId: (query) The unique ID of a germplasm (accession) to filter on (optional)
     - parameter studyDbId: (query) The unique ID of a studies to filter on (optional)
     - parameter locationDbId: (query) The unique ID of a location where these observations were collected (optional)
     - parameter trialDbId: (query) The unique ID of a trial to filter on (optional)
     - parameter programDbId: (query) The unique ID of a program to filter on (optional)
     - parameter seasonDbId: (query) The year or Phenotyping campaign of a multi-annual study (trees, grape, ...) (optional)
     - parameter observationUnitLevelName: (query) The Observation Unit Level. Returns only the observation unit of the specified Level. References ObservationUnit-&gt;observationUnitPosition-&gt;observationLevel-&gt;levelName (optional)
     - parameter observationUnitLevelOrder: (query) The Observation Unit Level Order Number. Returns only the observation unit of the specified Level. References ObservationUnit-&gt;observationUnitPosition-&gt;observationLevel-&gt;levelOrder (optional)
     - parameter observationUnitLevelCode: (query) The Observation Unit Level Code. This parameter should be used together with &#x60;observationUnitLevelName&#x60; or &#x60;observationUnitLevelOrder&#x60;. References ObservationUnit-&gt;observationUnitPosition-&gt;observationLevel-&gt;levelCode (optional)
     - parameter includeObservations: (query) Use this parameter to include a list of observations embedded in each ObservationUnit object.   CAUTION - Use this parameter at your own risk. It may return large, unpaginated lists of observation data. Only set this value to True if you are sure you need to. (optional)
     - parameter externalReferenceID: (query) An external reference ID. Could be a simple string or a URI. (use with &#x60;externalReferenceSource&#x60; parameter) (optional)
     - parameter externalReferenceSource: (query) An identifier for the source system or database of an external reference (use with &#x60;externalReferenceID&#x60; parameter) (optional)
     - parameter page: (query) Used to request a specific page of data to be returned.  The page indexing starts at 0 (the first page is &#x27;page&#x27;&#x3D; 0). Default is &#x60;0&#x60;. (optional)
     - parameter pageSize: (query) The size of the pages to be returned. Default is &#x60;1000&#x60;. (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)

     - returns: RequestBuilder<ObservationUnitListResponse> 
     */
    open class func observationunitsGetWithRequestBuilder(observationUnitDbId: String? = nil, germplasmDbId: String? = nil, studyDbId: String? = nil, locationDbId: String? = nil, trialDbId: String? = nil, programDbId: String? = nil, seasonDbId: String? = nil, observationUnitLevelName: String? = nil, observationUnitLevelOrder: String? = nil, observationUnitLevelCode: String? = nil, includeObservations: Bool? = nil, externalReferenceID: String? = nil, externalReferenceSource: String? = nil, page: Int? = nil, pageSize: Int? = nil, authorization: String? = nil) -> RequestBuilder<ObservationUnitListResponse> {
        let path = "/observationunits"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "observationUnitDbId": observationUnitDbId, 
                        "germplasmDbId": germplasmDbId, 
                        "studyDbId": studyDbId, 
                        "locationDbId": locationDbId, 
                        "trialDbId": trialDbId, 
                        "programDbId": programDbId, 
                        "seasonDbId": seasonDbId, 
                        "observationUnitLevelName": observationUnitLevelName, 
                        "observationUnitLevelOrder": observationUnitLevelOrder, 
                        "observationUnitLevelCode": observationUnitLevelCode, 
                        "includeObservations": includeObservations, 
                        "externalReferenceID": externalReferenceID, 
                        "externalReferenceSource": externalReferenceSource, 
                        "page": page?.encodeToJSON(), 
                        "pageSize": pageSize?.encodeToJSON()
        ])
        let nillableHeaders: [String: Any?] = [
                        "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ObservationUnitListResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     Get the details of a specific Observation Unit

     - parameter observationUnitDbId: (path) The unique ID of the specific Observation Unit 
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func observationunitsObservationUnitDbIdGet(observationUnitDbId: String, authorization: String? = nil, completion: @escaping ((_ data: ObservationUnitSingleResponse?,_ error: Error?) -> Void)) {
        observationunitsObservationUnitDbIdGetWithRequestBuilder(observationUnitDbId: observationUnitDbId, authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get the details of a specific Observation Unit
     - GET /observationunits/{observationUnitDbId}

     - :
       - type: http
       - name: AuthorizationToken
     - examples: [{contentType=application/json, example={
  "result" : {
    "observationUnitName" : "Plot 1",
    "trialDbId" : "776a609c",
    "externalReferences" : [ {
      "referenceID" : "doi:10.155454/12341234",
      "referenceSource" : "DOI"
    }, {
      "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
      "referenceSource" : "OBO Library"
    }, {
      "referenceID" : "75a50e76",
      "referenceSource" : "Remote Data Collection Upload Tool"
    } ],
    "observationUnitPosition" : {
      "entryType" : "TEST",
      "positionCoordinateYType" : "GRID_ROW",
      "positionCoordinateX" : "74",
      "positionCoordinateXType" : "GRID_COL",
      "observationLevel" : {
        "levelCode" : "Plot_123",
        "levelName" : "plot",
        "levelOrder" : 2
      },
      "observationLevelRelationships" : [ {
        "levelCode" : "Field_1",
        "levelName" : "field",
        "levelOrder" : 0
      }, {
        "levelCode" : "Block_12",
        "levelName" : "block",
        "levelOrder" : 1
      }, {
        "levelCode" : "Plot_123",
        "levelName" : "plot",
        "levelOrder" : 2
      } ],
      "geoCoordinates" : {
        "geometry" : {
          "coordinates" : [ -76.506042, 42.417373, 123 ],
          "type" : "Point"
        },
        "type" : "Feature"
      },
      "positionCoordinateY" : "03"
    },
    "locationName" : "Field Station Alpha",
    "studyName" : "Purple_Tomato_1",
    "seedLotDbId" : "261ecb09",
    "germplasmName" : "A0000001",
    "programDbId" : "2d763a7a",
    "germplasmDbId" : "e9d9ed57",
    "treatments" : [ {
      "modality" : "low fertilizer",
      "factor" : "fertilizer"
    }, {
      "modality" : "low fertilizer",
      "factor" : "fertilizer"
    } ],
    "studyDbId" : "9865addc",
    "locationDbId" : "0e208b20",
    "trialName" : "Purple Tomato",
    "programName" : "The Perfect Breeding Program",
    "observations" : [ {
      "observationUnitName" : "Plot 1",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "observationVariableName" : "Plant Height in meters",
      "germplasmName" : "A0000003",
      "germplasmDbId" : "2408ab11",
      "collector" : "917d3ae0",
      "observationDbId" : "ef24b615",
      "studyDbId" : "ef2829db",
      "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
      "observationVariableDbId" : "c403d107",
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "season" : {
        "year" : 2018,
        "seasonDbId" : "Spring_2018",
        "season" : "Spring"
      },
      "uploadedBy" : "a2f7f60b",
      "value" : "2.3",
      "observationUnitDbId" : "598111d4"
    }, {
      "observationUnitName" : "Plot 1",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "observationVariableName" : "Plant Height in meters",
      "germplasmName" : "A0000003",
      "germplasmDbId" : "2408ab11",
      "collector" : "917d3ae0",
      "observationDbId" : "ef24b615",
      "studyDbId" : "ef2829db",
      "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
      "observationVariableDbId" : "c403d107",
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "season" : {
        "year" : 2018,
        "seasonDbId" : "Spring_2018",
        "season" : "Spring"
      },
      "uploadedBy" : "a2f7f60b",
      "value" : "2.3",
      "observationUnitDbId" : "598111d4"
    } ],
    "additionalInfo" : {
      "key" : "additionalInfo"
    },
    "observationUnitDbId" : "8c67503c",
    "observationUnitPUI" : "http://pui.per/plot/1a9afc14"
  },
  "metadata" : {
    "pagination" : {
      "totalPages" : 1,
      "pageSize" : 1000,
      "currentPage" : 0,
      "totalCount" : 10
    },
    "datafiles" : [ {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    }, {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    } ],
    "status" : [ {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    }, {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    } ]
  },
  "@context" : [ "https://brapi.org/jsonld/context/metadata.jsonld" ]
}}]
     - parameter observationUnitDbId: (path) The unique ID of the specific Observation Unit 
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)

     - returns: RequestBuilder<ObservationUnitSingleResponse> 
     */
    open class func observationunitsObservationUnitDbIdGetWithRequestBuilder(observationUnitDbId: String, authorization: String? = nil) -> RequestBuilder<ObservationUnitSingleResponse> {
        var path = "/observationunits/{observationUnitDbId}"
        let observationUnitDbIdPreEscape = "\(observationUnitDbId)"
        let observationUnitDbIdPostEscape = observationUnitDbIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{observationUnitDbId}", with: observationUnitDbIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
                        "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ObservationUnitSingleResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     Update an existing Observation Units

     - parameter observationUnitDbId: (path) The unique ID of the specific Observation Unit 
     - parameter body: (body)  (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func observationunitsObservationUnitDbIdPut(observationUnitDbId: String, body: ObservationUnitNewRequest? = nil, authorization: String? = nil, completion: @escaping ((_ data: ObservationUnitSingleResponse?,_ error: Error?) -> Void)) {
        observationunitsObservationUnitDbIdPutWithRequestBuilder(observationUnitDbId: observationUnitDbId, body: body, authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Update an existing Observation Units
     - PUT /observationunits/{observationUnitDbId}

     - :
       - type: http
       - name: AuthorizationToken
     - examples: [{contentType=application/json, example={
  "result" : {
    "observationUnitName" : "Plot 1",
    "trialDbId" : "776a609c",
    "externalReferences" : [ {
      "referenceID" : "doi:10.155454/12341234",
      "referenceSource" : "DOI"
    }, {
      "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
      "referenceSource" : "OBO Library"
    }, {
      "referenceID" : "75a50e76",
      "referenceSource" : "Remote Data Collection Upload Tool"
    } ],
    "observationUnitPosition" : {
      "entryType" : "TEST",
      "positionCoordinateYType" : "GRID_ROW",
      "positionCoordinateX" : "74",
      "positionCoordinateXType" : "GRID_COL",
      "observationLevel" : {
        "levelCode" : "Plot_123",
        "levelName" : "plot",
        "levelOrder" : 2
      },
      "observationLevelRelationships" : [ {
        "levelCode" : "Field_1",
        "levelName" : "field",
        "levelOrder" : 0
      }, {
        "levelCode" : "Block_12",
        "levelName" : "block",
        "levelOrder" : 1
      }, {
        "levelCode" : "Plot_123",
        "levelName" : "plot",
        "levelOrder" : 2
      } ],
      "geoCoordinates" : {
        "geometry" : {
          "coordinates" : [ -76.506042, 42.417373, 123 ],
          "type" : "Point"
        },
        "type" : "Feature"
      },
      "positionCoordinateY" : "03"
    },
    "locationName" : "Field Station Alpha",
    "studyName" : "Purple_Tomato_1",
    "seedLotDbId" : "261ecb09",
    "germplasmName" : "A0000001",
    "programDbId" : "2d763a7a",
    "germplasmDbId" : "e9d9ed57",
    "treatments" : [ {
      "modality" : "low fertilizer",
      "factor" : "fertilizer"
    }, {
      "modality" : "low fertilizer",
      "factor" : "fertilizer"
    } ],
    "studyDbId" : "9865addc",
    "locationDbId" : "0e208b20",
    "trialName" : "Purple Tomato",
    "programName" : "The Perfect Breeding Program",
    "observations" : [ {
      "observationUnitName" : "Plot 1",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "observationVariableName" : "Plant Height in meters",
      "germplasmName" : "A0000003",
      "germplasmDbId" : "2408ab11",
      "collector" : "917d3ae0",
      "observationDbId" : "ef24b615",
      "studyDbId" : "ef2829db",
      "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
      "observationVariableDbId" : "c403d107",
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "season" : {
        "year" : 2018,
        "seasonDbId" : "Spring_2018",
        "season" : "Spring"
      },
      "uploadedBy" : "a2f7f60b",
      "value" : "2.3",
      "observationUnitDbId" : "598111d4"
    }, {
      "observationUnitName" : "Plot 1",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "observationVariableName" : "Plant Height in meters",
      "germplasmName" : "A0000003",
      "germplasmDbId" : "2408ab11",
      "collector" : "917d3ae0",
      "observationDbId" : "ef24b615",
      "studyDbId" : "ef2829db",
      "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
      "observationVariableDbId" : "c403d107",
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "season" : {
        "year" : 2018,
        "seasonDbId" : "Spring_2018",
        "season" : "Spring"
      },
      "uploadedBy" : "a2f7f60b",
      "value" : "2.3",
      "observationUnitDbId" : "598111d4"
    } ],
    "additionalInfo" : {
      "key" : "additionalInfo"
    },
    "observationUnitDbId" : "8c67503c",
    "observationUnitPUI" : "http://pui.per/plot/1a9afc14"
  },
  "metadata" : {
    "pagination" : {
      "totalPages" : 1,
      "pageSize" : 1000,
      "currentPage" : 0,
      "totalCount" : 10
    },
    "datafiles" : [ {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    }, {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    } ],
    "status" : [ {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    }, {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    } ]
  },
  "@context" : [ "https://brapi.org/jsonld/context/metadata.jsonld" ]
}}]
     - parameter observationUnitDbId: (path) The unique ID of the specific Observation Unit 
     - parameter body: (body)  (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)

     - returns: RequestBuilder<ObservationUnitSingleResponse> 
     */
    open class func observationunitsObservationUnitDbIdPutWithRequestBuilder(observationUnitDbId: String, body: ObservationUnitNewRequest? = nil, authorization: String? = nil) -> RequestBuilder<ObservationUnitSingleResponse> {
        var path = "/observationunits/{observationUnitDbId}"
        let observationUnitDbIdPreEscape = "\(observationUnitDbId)"
        let observationUnitDbIdPostEscape = observationUnitDbIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{observationUnitDbId}", with: observationUnitDbIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
                        "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ObservationUnitSingleResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     Add new Observation Units

     - parameter body: (body)  (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func observationunitsPost(body: [ObservationUnitNewRequest]? = nil, authorization: String? = nil, completion: @escaping ((_ data: ObservationUnitListResponse?,_ error: Error?) -> Void)) {
        observationunitsPostWithRequestBuilder(body: body, authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Add new Observation Units
     - POST /observationunits

     - :
       - type: http
       - name: AuthorizationToken
     - examples: [{contentType=application/json, example={
  "result" : {
    "data" : [ {
      "observationUnitName" : "Plot 1",
      "trialDbId" : "776a609c",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "observationUnitPosition" : {
        "entryType" : "TEST",
        "positionCoordinateYType" : "GRID_ROW",
        "positionCoordinateX" : "74",
        "positionCoordinateXType" : "GRID_COL",
        "observationLevel" : {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        },
        "observationLevelRelationships" : [ {
          "levelCode" : "Field_1",
          "levelName" : "field",
          "levelOrder" : 0
        }, {
          "levelCode" : "Block_12",
          "levelName" : "block",
          "levelOrder" : 1
        }, {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        } ],
        "geoCoordinates" : {
          "geometry" : {
            "coordinates" : [ -76.506042, 42.417373, 123 ],
            "type" : "Point"
          },
          "type" : "Feature"
        },
        "positionCoordinateY" : "03"
      },
      "locationName" : "Field Station Alpha",
      "studyName" : "Purple_Tomato_1",
      "seedLotDbId" : "261ecb09",
      "germplasmName" : "A0000001",
      "programDbId" : "2d763a7a",
      "germplasmDbId" : "e9d9ed57",
      "treatments" : [ {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      }, {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      } ],
      "studyDbId" : "9865addc",
      "locationDbId" : "0e208b20",
      "trialName" : "Purple Tomato",
      "programName" : "The Perfect Breeding Program",
      "observations" : [ {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      }, {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      } ],
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "observationUnitDbId" : "8c67503c",
      "observationUnitPUI" : "http://pui.per/plot/1a9afc14"
    }, {
      "observationUnitName" : "Plot 1",
      "trialDbId" : "776a609c",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "observationUnitPosition" : {
        "entryType" : "TEST",
        "positionCoordinateYType" : "GRID_ROW",
        "positionCoordinateX" : "74",
        "positionCoordinateXType" : "GRID_COL",
        "observationLevel" : {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        },
        "observationLevelRelationships" : [ {
          "levelCode" : "Field_1",
          "levelName" : "field",
          "levelOrder" : 0
        }, {
          "levelCode" : "Block_12",
          "levelName" : "block",
          "levelOrder" : 1
        }, {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        } ],
        "geoCoordinates" : {
          "geometry" : {
            "coordinates" : [ -76.506042, 42.417373, 123 ],
            "type" : "Point"
          },
          "type" : "Feature"
        },
        "positionCoordinateY" : "03"
      },
      "locationName" : "Field Station Alpha",
      "studyName" : "Purple_Tomato_1",
      "seedLotDbId" : "261ecb09",
      "germplasmName" : "A0000001",
      "programDbId" : "2d763a7a",
      "germplasmDbId" : "e9d9ed57",
      "treatments" : [ {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      }, {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      } ],
      "studyDbId" : "9865addc",
      "locationDbId" : "0e208b20",
      "trialName" : "Purple Tomato",
      "programName" : "The Perfect Breeding Program",
      "observations" : [ {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      }, {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      } ],
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "observationUnitDbId" : "8c67503c",
      "observationUnitPUI" : "http://pui.per/plot/1a9afc14"
    } ]
  },
  "metadata" : {
    "pagination" : {
      "totalPages" : 1,
      "pageSize" : 1000,
      "currentPage" : 0,
      "totalCount" : 10
    },
    "datafiles" : [ {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    }, {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    } ],
    "status" : [ {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    }, {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    } ]
  },
  "@context" : [ "https://brapi.org/jsonld/context/metadata.jsonld" ]
}}]
     - parameter body: (body)  (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)

     - returns: RequestBuilder<ObservationUnitListResponse> 
     */
    open class func observationunitsPostWithRequestBuilder(body: [ObservationUnitNewRequest]? = nil, authorization: String? = nil) -> RequestBuilder<ObservationUnitListResponse> {
        let path = "/observationunits"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
                        "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ObservationUnitListResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     Update a set of Observation Units

     - parameter body: (body)  (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func observationunitsPut(body: [String:ObservationUnitNewRequest]? = nil, authorization: String? = nil, completion: @escaping ((_ data: ObservationUnitListResponse?,_ error: Error?) -> Void)) {
        observationunitsPutWithRequestBuilder(body: body, authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Update a set of Observation Units
     - PUT /observationunits

     - :
       - type: http
       - name: AuthorizationToken
     - examples: [{contentType=application/json, example={
  "result" : {
    "data" : [ {
      "observationUnitName" : "Plot 1",
      "trialDbId" : "776a609c",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "observationUnitPosition" : {
        "entryType" : "TEST",
        "positionCoordinateYType" : "GRID_ROW",
        "positionCoordinateX" : "74",
        "positionCoordinateXType" : "GRID_COL",
        "observationLevel" : {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        },
        "observationLevelRelationships" : [ {
          "levelCode" : "Field_1",
          "levelName" : "field",
          "levelOrder" : 0
        }, {
          "levelCode" : "Block_12",
          "levelName" : "block",
          "levelOrder" : 1
        }, {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        } ],
        "geoCoordinates" : {
          "geometry" : {
            "coordinates" : [ -76.506042, 42.417373, 123 ],
            "type" : "Point"
          },
          "type" : "Feature"
        },
        "positionCoordinateY" : "03"
      },
      "locationName" : "Field Station Alpha",
      "studyName" : "Purple_Tomato_1",
      "seedLotDbId" : "261ecb09",
      "germplasmName" : "A0000001",
      "programDbId" : "2d763a7a",
      "germplasmDbId" : "e9d9ed57",
      "treatments" : [ {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      }, {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      } ],
      "studyDbId" : "9865addc",
      "locationDbId" : "0e208b20",
      "trialName" : "Purple Tomato",
      "programName" : "The Perfect Breeding Program",
      "observations" : [ {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      }, {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      } ],
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "observationUnitDbId" : "8c67503c",
      "observationUnitPUI" : "http://pui.per/plot/1a9afc14"
    }, {
      "observationUnitName" : "Plot 1",
      "trialDbId" : "776a609c",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "observationUnitPosition" : {
        "entryType" : "TEST",
        "positionCoordinateYType" : "GRID_ROW",
        "positionCoordinateX" : "74",
        "positionCoordinateXType" : "GRID_COL",
        "observationLevel" : {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        },
        "observationLevelRelationships" : [ {
          "levelCode" : "Field_1",
          "levelName" : "field",
          "levelOrder" : 0
        }, {
          "levelCode" : "Block_12",
          "levelName" : "block",
          "levelOrder" : 1
        }, {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        } ],
        "geoCoordinates" : {
          "geometry" : {
            "coordinates" : [ -76.506042, 42.417373, 123 ],
            "type" : "Point"
          },
          "type" : "Feature"
        },
        "positionCoordinateY" : "03"
      },
      "locationName" : "Field Station Alpha",
      "studyName" : "Purple_Tomato_1",
      "seedLotDbId" : "261ecb09",
      "germplasmName" : "A0000001",
      "programDbId" : "2d763a7a",
      "germplasmDbId" : "e9d9ed57",
      "treatments" : [ {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      }, {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      } ],
      "studyDbId" : "9865addc",
      "locationDbId" : "0e208b20",
      "trialName" : "Purple Tomato",
      "programName" : "The Perfect Breeding Program",
      "observations" : [ {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      }, {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      } ],
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "observationUnitDbId" : "8c67503c",
      "observationUnitPUI" : "http://pui.per/plot/1a9afc14"
    } ]
  },
  "metadata" : {
    "pagination" : {
      "totalPages" : 1,
      "pageSize" : 1000,
      "currentPage" : 0,
      "totalCount" : 10
    },
    "datafiles" : [ {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    }, {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    } ],
    "status" : [ {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    }, {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    } ]
  },
  "@context" : [ "https://brapi.org/jsonld/context/metadata.jsonld" ]
}}]
     - parameter body: (body)  (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)

     - returns: RequestBuilder<ObservationUnitListResponse> 
     */
    open class func observationunitsPutWithRequestBuilder(body: [String:ObservationUnitNewRequest]? = nil, authorization: String? = nil) -> RequestBuilder<ObservationUnitListResponse> {
        let path = "/observationunits"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
                        "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ObservationUnitListResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     Get a list of Observations in a table format

     - parameter accept: (header) The requested content type which should be returned by the server 
     - parameter observationUnitDbId: (query) The unique ID of an Observation Unit (optional)
     - parameter germplasmDbId: (query) The unique ID of a germplasm (accession) to filter on (optional)
     - parameter observationVariableDbId: (query) The unique ID of an observation variable (optional)
     - parameter studyDbId: (query) The unique ID of a studies to filter on (optional)
     - parameter locationDbId: (query) The unique ID of a location where these observations were collected (optional)
     - parameter trialDbId: (query) The unique ID of a trial to filter on (optional)
     - parameter programDbId: (query) The unique ID of a program to filter on (optional)
     - parameter seasonDbId: (query) The year or Phenotyping campaign of a multi-annual study (trees, grape, ...) (optional)
     - parameter observationLevel: (query) The type of the observationUnit. Returns only the observation unit of the specified type; the parent levels ID can be accessed through observationUnitStructure. (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func observationunitsTableGet(accept: WSMIMEDataTypes, observationUnitDbId: String? = nil, germplasmDbId: String? = nil, observationVariableDbId: String? = nil, studyDbId: String? = nil, locationDbId: String? = nil, trialDbId: String? = nil, programDbId: String? = nil, seasonDbId: String? = nil, observationLevel: String? = nil, authorization: String? = nil, completion: @escaping ((_ data: ObservationUnitTableResponse?,_ error: Error?) -> Void)) {
        observationunitsTableGetWithRequestBuilder(accept: accept, observationUnitDbId: observationUnitDbId, germplasmDbId: germplasmDbId, observationVariableDbId: observationVariableDbId, studyDbId: studyDbId, locationDbId: locationDbId, trialDbId: trialDbId, programDbId: programDbId, seasonDbId: seasonDbId, observationLevel: observationLevel, authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get a list of Observations in a table format
     - GET /observationunits/table

     - :
       - type: http
       - name: AuthorizationToken
     - examples: [{contentType=application/json, example={
  "result" : {
    "data" : [ [ "f3a8a3db", "Plant Alpha", "0fe3e48b", "2017 Plant Study", "06307ec0", "A0043001", "76.50106681", "42.44409301", "2017", "Field_1", "Plot_11", "SubPlot_111", "Plant_1111", "Pot_1111", "Block_11", "Entry_11", "Rep_11", "25.3", "3", "50.75" ], [ "05d1b011", "Plant Beta", "0fe3e48b", "2017 Plant Study", "59d435cd", "A0043002", "76.50106683", "42.44409301", "2017", "Field_1", "Plot_11", "SubPlot_112", "Plant_1122", "Pot_1122", "Block_11", "Entry_11", "Rep_12", "27.9", "1", "45.345" ], [ "67e2d87c", "Plant Gamma", "0fe3e48b", "2017 Plant Study", "06307ec0", "A0043001", "76.50106681", "42.44409356", "2017", "Field_1", "Plot_12", "SubPlot_123", "Plant_1233", "Pot_1233", "Block_12", "Entry_12", "Rep_11", "25.5", "3", "50.76" ], [ "d98d0d4c", "Plant Epsilon", "0fe3e48b", "2017 Plant Study", "59d435cd", "A0043002", "76.50106683", "42.44409356", "2017", "Field_1", "Plot_12", "SubPlot_124", "Plant_1244", "Pot_1244", "Block_12", "Entry_12", "Rep_12", "28.9", "0", "46.5" ] ],
    "headerRow" : [ "observationUnitDbId", "observationUnitName", "studyDbId", "studyName", "germplasmDbId", "germplasmName", "positionCoordinateX", "positionCoordinateY", "year", "field", "plot", "sub-plot", "plant", "pot", "block", "entry", "rep" ],
    "observationVariables" : [ {
      "observationVariableDbId" : "367aa1a9",
      "observationVariableName" : "Plant height"
    }, {
      "observationVariableDbId" : "2acb934c",
      "observationVariableName" : "Carotenoid"
    }, {
      "observationVariableDbId" : "85a21ce1",
      "observationVariableName" : "Root color"
    }, {
      "observationVariableDbId" : "46f590e5",
      "observationVariableName" : "Virus severity"
    } ]
  },
  "metadata" : {
    "pagination" : {
      "totalPages" : 1,
      "pageSize" : 1000,
      "currentPage" : 0,
      "totalCount" : 10
    },
    "datafiles" : [ {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    }, {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    } ],
    "status" : [ {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    }, {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    } ]
  },
  "@context" : [ "https://brapi.org/jsonld/context/metadata.jsonld" ]
}}]
     - parameter accept: (header) The requested content type which should be returned by the server 
     - parameter observationUnitDbId: (query) The unique ID of an Observation Unit (optional)
     - parameter germplasmDbId: (query) The unique ID of a germplasm (accession) to filter on (optional)
     - parameter observationVariableDbId: (query) The unique ID of an observation variable (optional)
     - parameter studyDbId: (query) The unique ID of a studies to filter on (optional)
     - parameter locationDbId: (query) The unique ID of a location where these observations were collected (optional)
     - parameter trialDbId: (query) The unique ID of a trial to filter on (optional)
     - parameter programDbId: (query) The unique ID of a program to filter on (optional)
     - parameter seasonDbId: (query) The year or Phenotyping campaign of a multi-annual study (trees, grape, ...) (optional)
     - parameter observationLevel: (query) The type of the observationUnit. Returns only the observation unit of the specified type; the parent levels ID can be accessed through observationUnitStructure. (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)

     - returns: RequestBuilder<ObservationUnitTableResponse> 
     */
    open class func observationunitsTableGetWithRequestBuilder(accept: WSMIMEDataTypes, observationUnitDbId: String? = nil, germplasmDbId: String? = nil, observationVariableDbId: String? = nil, studyDbId: String? = nil, locationDbId: String? = nil, trialDbId: String? = nil, programDbId: String? = nil, seasonDbId: String? = nil, observationLevel: String? = nil, authorization: String? = nil) -> RequestBuilder<ObservationUnitTableResponse> {
        let path = "/observationunits/table"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "observationUnitDbId": observationUnitDbId, 
                        "germplasmDbId": germplasmDbId, 
                        "observationVariableDbId": observationVariableDbId, 
                        "studyDbId": studyDbId, 
                        "locationDbId": locationDbId, 
                        "trialDbId": trialDbId, 
                        "programDbId": programDbId, 
                        "seasonDbId": seasonDbId, 
                        "observationLevel": observationLevel
        ])
        let nillableHeaders: [String: Any?] = [
                        "Accept": accept,
                        "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ObservationUnitTableResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     Submit a search request for `ObservationUnits`

     - parameter body: (body)  (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func searchObservationunitsPost(body: ObservationUnitSearchRequest? = nil, authorization: String? = nil, completion: @escaping ((_ data: ObservationUnitListResponse?,_ error: Error?) -> Void)) {
        searchObservationunitsPostWithRequestBuilder(body: body, authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Submit a search request for `ObservationUnits`
     - POST /search/observationunits

     - :
       - type: http
       - name: AuthorizationToken
     - examples: [{contentType=application/json, example={
  "result" : {
    "data" : [ {
      "observationUnitName" : "Plot 1",
      "trialDbId" : "776a609c",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "observationUnitPosition" : {
        "entryType" : "TEST",
        "positionCoordinateYType" : "GRID_ROW",
        "positionCoordinateX" : "74",
        "positionCoordinateXType" : "GRID_COL",
        "observationLevel" : {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        },
        "observationLevelRelationships" : [ {
          "levelCode" : "Field_1",
          "levelName" : "field",
          "levelOrder" : 0
        }, {
          "levelCode" : "Block_12",
          "levelName" : "block",
          "levelOrder" : 1
        }, {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        } ],
        "geoCoordinates" : {
          "geometry" : {
            "coordinates" : [ -76.506042, 42.417373, 123 ],
            "type" : "Point"
          },
          "type" : "Feature"
        },
        "positionCoordinateY" : "03"
      },
      "locationName" : "Field Station Alpha",
      "studyName" : "Purple_Tomato_1",
      "seedLotDbId" : "261ecb09",
      "germplasmName" : "A0000001",
      "programDbId" : "2d763a7a",
      "germplasmDbId" : "e9d9ed57",
      "treatments" : [ {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      }, {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      } ],
      "studyDbId" : "9865addc",
      "locationDbId" : "0e208b20",
      "trialName" : "Purple Tomato",
      "programName" : "The Perfect Breeding Program",
      "observations" : [ {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      }, {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      } ],
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "observationUnitDbId" : "8c67503c",
      "observationUnitPUI" : "http://pui.per/plot/1a9afc14"
    }, {
      "observationUnitName" : "Plot 1",
      "trialDbId" : "776a609c",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "observationUnitPosition" : {
        "entryType" : "TEST",
        "positionCoordinateYType" : "GRID_ROW",
        "positionCoordinateX" : "74",
        "positionCoordinateXType" : "GRID_COL",
        "observationLevel" : {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        },
        "observationLevelRelationships" : [ {
          "levelCode" : "Field_1",
          "levelName" : "field",
          "levelOrder" : 0
        }, {
          "levelCode" : "Block_12",
          "levelName" : "block",
          "levelOrder" : 1
        }, {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        } ],
        "geoCoordinates" : {
          "geometry" : {
            "coordinates" : [ -76.506042, 42.417373, 123 ],
            "type" : "Point"
          },
          "type" : "Feature"
        },
        "positionCoordinateY" : "03"
      },
      "locationName" : "Field Station Alpha",
      "studyName" : "Purple_Tomato_1",
      "seedLotDbId" : "261ecb09",
      "germplasmName" : "A0000001",
      "programDbId" : "2d763a7a",
      "germplasmDbId" : "e9d9ed57",
      "treatments" : [ {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      }, {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      } ],
      "studyDbId" : "9865addc",
      "locationDbId" : "0e208b20",
      "trialName" : "Purple Tomato",
      "programName" : "The Perfect Breeding Program",
      "observations" : [ {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      }, {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      } ],
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "observationUnitDbId" : "8c67503c",
      "observationUnitPUI" : "http://pui.per/plot/1a9afc14"
    } ]
  },
  "metadata" : {
    "pagination" : {
      "totalPages" : 1,
      "pageSize" : 1000,
      "currentPage" : 0,
      "totalCount" : 10
    },
    "datafiles" : [ {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    }, {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    } ],
    "status" : [ {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    }, {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    } ]
  },
  "@context" : [ "https://brapi.org/jsonld/context/metadata.jsonld" ]
}}]
     - parameter body: (body)  (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)

     - returns: RequestBuilder<ObservationUnitListResponse> 
     */
    open class func searchObservationunitsPostWithRequestBuilder(body: ObservationUnitSearchRequest? = nil, authorization: String? = nil) -> RequestBuilder<ObservationUnitListResponse> {
        let path = "/search/observationunits"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
                        "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ObservationUnitListResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     Get the results of a `ObservationUnits` search request

     - parameter searchResultsDbId: (path) Unique identifier which references the search results 
     - parameter page: (query) Used to request a specific page of data to be returned.  The page indexing starts at 0 (the first page is &#x27;page&#x27;&#x3D; 0). Default is &#x60;0&#x60;. (optional)
     - parameter pageSize: (query) The size of the pages to be returned. Default is &#x60;1000&#x60;. (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func searchObservationunitsSearchResultsDbIdGet(searchResultsDbId: String, page: Int? = nil, pageSize: Int? = nil, authorization: String? = nil, completion: @escaping ((_ data: ObservationUnitListResponse?,_ error: Error?) -> Void)) {
        searchObservationunitsSearchResultsDbIdGetWithRequestBuilder(searchResultsDbId: searchResultsDbId, page: page, pageSize: pageSize, authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get the results of a `ObservationUnits` search request
     - GET /search/observationunits/{searchResultsDbId}

     - :
       - type: http
       - name: AuthorizationToken
     - examples: [{contentType=application/json, example={
  "result" : {
    "data" : [ {
      "observationUnitName" : "Plot 1",
      "trialDbId" : "776a609c",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "observationUnitPosition" : {
        "entryType" : "TEST",
        "positionCoordinateYType" : "GRID_ROW",
        "positionCoordinateX" : "74",
        "positionCoordinateXType" : "GRID_COL",
        "observationLevel" : {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        },
        "observationLevelRelationships" : [ {
          "levelCode" : "Field_1",
          "levelName" : "field",
          "levelOrder" : 0
        }, {
          "levelCode" : "Block_12",
          "levelName" : "block",
          "levelOrder" : 1
        }, {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        } ],
        "geoCoordinates" : {
          "geometry" : {
            "coordinates" : [ -76.506042, 42.417373, 123 ],
            "type" : "Point"
          },
          "type" : "Feature"
        },
        "positionCoordinateY" : "03"
      },
      "locationName" : "Field Station Alpha",
      "studyName" : "Purple_Tomato_1",
      "seedLotDbId" : "261ecb09",
      "germplasmName" : "A0000001",
      "programDbId" : "2d763a7a",
      "germplasmDbId" : "e9d9ed57",
      "treatments" : [ {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      }, {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      } ],
      "studyDbId" : "9865addc",
      "locationDbId" : "0e208b20",
      "trialName" : "Purple Tomato",
      "programName" : "The Perfect Breeding Program",
      "observations" : [ {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      }, {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      } ],
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "observationUnitDbId" : "8c67503c",
      "observationUnitPUI" : "http://pui.per/plot/1a9afc14"
    }, {
      "observationUnitName" : "Plot 1",
      "trialDbId" : "776a609c",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "observationUnitPosition" : {
        "entryType" : "TEST",
        "positionCoordinateYType" : "GRID_ROW",
        "positionCoordinateX" : "74",
        "positionCoordinateXType" : "GRID_COL",
        "observationLevel" : {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        },
        "observationLevelRelationships" : [ {
          "levelCode" : "Field_1",
          "levelName" : "field",
          "levelOrder" : 0
        }, {
          "levelCode" : "Block_12",
          "levelName" : "block",
          "levelOrder" : 1
        }, {
          "levelCode" : "Plot_123",
          "levelName" : "plot",
          "levelOrder" : 2
        } ],
        "geoCoordinates" : {
          "geometry" : {
            "coordinates" : [ -76.506042, 42.417373, 123 ],
            "type" : "Point"
          },
          "type" : "Feature"
        },
        "positionCoordinateY" : "03"
      },
      "locationName" : "Field Station Alpha",
      "studyName" : "Purple_Tomato_1",
      "seedLotDbId" : "261ecb09",
      "germplasmName" : "A0000001",
      "programDbId" : "2d763a7a",
      "germplasmDbId" : "e9d9ed57",
      "treatments" : [ {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      }, {
        "modality" : "low fertilizer",
        "factor" : "fertilizer"
      } ],
      "studyDbId" : "9865addc",
      "locationDbId" : "0e208b20",
      "trialName" : "Purple Tomato",
      "programName" : "The Perfect Breeding Program",
      "observations" : [ {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      }, {
        "observationUnitName" : "Plot 1",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "observationVariableName" : "Plant Height in meters",
        "germplasmName" : "A0000003",
        "germplasmDbId" : "2408ab11",
        "collector" : "917d3ae0",
        "observationDbId" : "ef24b615",
        "studyDbId" : "ef2829db",
        "observationTimeStamp" : "2000-01-23T04:56:07.000+00:00",
        "observationVariableDbId" : "c403d107",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "season" : {
          "year" : 2018,
          "seasonDbId" : "Spring_2018",
          "season" : "Spring"
        },
        "uploadedBy" : "a2f7f60b",
        "value" : "2.3",
        "observationUnitDbId" : "598111d4"
      } ],
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "observationUnitDbId" : "8c67503c",
      "observationUnitPUI" : "http://pui.per/plot/1a9afc14"
    } ]
  },
  "metadata" : {
    "pagination" : {
      "totalPages" : 1,
      "pageSize" : 1000,
      "currentPage" : 0,
      "totalCount" : 10
    },
    "datafiles" : [ {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    }, {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    } ],
    "status" : [ {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    }, {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    } ]
  },
  "@context" : [ "https://brapi.org/jsonld/context/metadata.jsonld" ]
}}]
     - parameter searchResultsDbId: (path) Unique identifier which references the search results 
     - parameter page: (query) Used to request a specific page of data to be returned.  The page indexing starts at 0 (the first page is &#x27;page&#x27;&#x3D; 0). Default is &#x60;0&#x60;. (optional)
     - parameter pageSize: (query) The size of the pages to be returned. Default is &#x60;1000&#x60;. (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)

     - returns: RequestBuilder<ObservationUnitListResponse> 
     */
    open class func searchObservationunitsSearchResultsDbIdGetWithRequestBuilder(searchResultsDbId: String, page: Int? = nil, pageSize: Int? = nil, authorization: String? = nil) -> RequestBuilder<ObservationUnitListResponse> {
        var path = "/search/observationunits/{searchResultsDbId}"
        let searchResultsDbIdPreEscape = "\(searchResultsDbId)"
        let searchResultsDbIdPostEscape = searchResultsDbIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{searchResultsDbId}", with: searchResultsDbIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "page": page?.encodeToJSON(), 
                        "pageSize": pageSize?.encodeToJSON()
        ])
        let nillableHeaders: [String: Any?] = [
                        "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ObservationUnitListResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
}
