//
// ObservationVariablesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class ObservationVariablesAPI {
    /**
     Submit a search request for Observation `Variables`

     - parameter body: (body)  (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func searchVariablesPost(body: ObservationVariableSearchRequest? = nil, authorization: String? = nil, completion: @escaping ((_ data: ObservationVariableListResponse?,_ error: Error?) -> Void)) {
        searchVariablesPostWithRequestBuilder(body: body, authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Submit a search request for Observation `Variables`
     - POST /search/variables

     - :
       - type: http
       - name: AuthorizationToken
     - examples: [{contentType=application/json, example={
  "result" : {
    "data" : [ {
      "commonCropName" : "Maize",
      "documentationURL" : "https://wiki.brapi.org/documentation.html",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "method" : {
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "methodClass" : "Measurement",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "description" : "A measuring tape was used",
        "formula" : "a^2 + b^2 = c^2",
        "methodName" : "Measuring Tape",
        "methodDbId" : "0adb2764",
        "ontologyReference" : {
          "ontologyDbId" : "6b071868",
          "ontologyName" : "The Crop Ontology",
          "documentationLinks" : [ {
            "type" : "OBO",
            "URL" : "http://purl.obolibrary.org/obo/ro.owl"
          }, {
            "type" : "OBO",
            "URL" : "http://purl.obolibrary.org/obo/ro.owl"
          } ],
          "version" : "7.2.3"
        },
        "bibliographicalReference" : "Smith, 1893, Really Cool Paper, Popular Journal"
      },
      "defaultValue" : "2.0",
      "scientist" : "Dr. Bob Robertson",
      "synonyms" : [ "Maize Height", "Stalk Height", "Corn Height" ],
      "observationVariableName" : "Variable Name",
      "scale" : {
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "decimalPlaces" : 2,
        "dataType" : "Numerical",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "scaleDbId" : "af730171",
        "scaleName" : "Meters",
        "validValues" : {
          "min" : 2,
          "max" : 9999,
          "categories" : [ {
            "label" : "low",
            "value" : "0"
          }, {
            "label" : "medium",
            "value" : "5"
          }, {
            "label" : "high",
            "value" : "10"
          } ]
        }
      },
      "language" : "en",
      "contextOfUse" : [ "Trial evaluation", "Nursery evaluation" ],
      "submissionTimestamp" : "2000-01-23T04:56:07.000+00:00",
      "institution" : "The BrAPI Institute",
      "growthStage" : "flowering",
      "observationVariableDbId" : "b9b7edd1",
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "trait" : {
        "traitName" : "Height",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "synonyms" : [ "Height", "Plant Height", "Stalk Height", "Canopy Height" ],
        "traitDbId" : "9b2e34f5",
        "alternativeAbbreviations" : [ "H", "PH", "H1" ],
        "mainAbbreviation" : "PH",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "attribute" : "height",
        "traitDescription" : "The height of the plant",
        "entity" : "Stalk",
        "status" : "recommended",
        "traitClass" : "phenological"
      },
      "status" : "recommended"
    }, {
      "commonCropName" : "Maize",
      "documentationURL" : "https://wiki.brapi.org/documentation.html",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "method" : {
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "methodClass" : "Measurement",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "description" : "A measuring tape was used",
        "formula" : "a^2 + b^2 = c^2",
        "methodName" : "Measuring Tape",
        "methodDbId" : "0adb2764",
        "ontologyReference" : {
          "ontologyDbId" : "6b071868",
          "ontologyName" : "The Crop Ontology",
          "documentationLinks" : [ {
            "type" : "OBO",
            "URL" : "http://purl.obolibrary.org/obo/ro.owl"
          }, {
            "type" : "OBO",
            "URL" : "http://purl.obolibrary.org/obo/ro.owl"
          } ],
          "version" : "7.2.3"
        },
        "bibliographicalReference" : "Smith, 1893, Really Cool Paper, Popular Journal"
      },
      "defaultValue" : "2.0",
      "scientist" : "Dr. Bob Robertson",
      "synonyms" : [ "Maize Height", "Stalk Height", "Corn Height" ],
      "observationVariableName" : "Variable Name",
      "scale" : {
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "decimalPlaces" : 2,
        "dataType" : "Numerical",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "scaleDbId" : "af730171",
        "scaleName" : "Meters",
        "validValues" : {
          "min" : 2,
          "max" : 9999,
          "categories" : [ {
            "label" : "low",
            "value" : "0"
          }, {
            "label" : "medium",
            "value" : "5"
          }, {
            "label" : "high",
            "value" : "10"
          } ]
        }
      },
      "language" : "en",
      "contextOfUse" : [ "Trial evaluation", "Nursery evaluation" ],
      "submissionTimestamp" : "2000-01-23T04:56:07.000+00:00",
      "institution" : "The BrAPI Institute",
      "growthStage" : "flowering",
      "observationVariableDbId" : "b9b7edd1",
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "trait" : {
        "traitName" : "Height",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "synonyms" : [ "Height", "Plant Height", "Stalk Height", "Canopy Height" ],
        "traitDbId" : "9b2e34f5",
        "alternativeAbbreviations" : [ "H", "PH", "H1" ],
        "mainAbbreviation" : "PH",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "attribute" : "height",
        "traitDescription" : "The height of the plant",
        "entity" : "Stalk",
        "status" : "recommended",
        "traitClass" : "phenological"
      },
      "status" : "recommended"
    } ]
  },
  "metadata" : {
    "pagination" : {
      "totalPages" : 1,
      "pageSize" : 1000,
      "currentPage" : 0,
      "totalCount" : 10
    },
    "datafiles" : [ {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    }, {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    } ],
    "status" : [ {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    }, {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    } ]
  },
  "@context" : [ "https://brapi.org/jsonld/context/metadata.jsonld" ]
}}]
     - parameter body: (body)  (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)

     - returns: RequestBuilder<ObservationVariableListResponse> 
     */
    open class func searchVariablesPostWithRequestBuilder(body: ObservationVariableSearchRequest? = nil, authorization: String? = nil) -> RequestBuilder<ObservationVariableListResponse> {
        let path = "/search/variables"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
                        "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ObservationVariableListResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     Get the results of a Observation `variables` search request

     - parameter searchResultsDbId: (path) Unique identifier which references the search results 
     - parameter page: (query) Used to request a specific page of data to be returned.  The page indexing starts at 0 (the first page is &#x27;page&#x27;&#x3D; 0). Default is &#x60;0&#x60;. (optional)
     - parameter pageSize: (query) The size of the pages to be returned. Default is &#x60;1000&#x60;. (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func searchVariablesSearchResultsDbIdGet(searchResultsDbId: String, page: Int? = nil, pageSize: Int? = nil, authorization: String? = nil, completion: @escaping ((_ data: ObservationVariableListResponse?,_ error: Error?) -> Void)) {
        searchVariablesSearchResultsDbIdGetWithRequestBuilder(searchResultsDbId: searchResultsDbId, page: page, pageSize: pageSize, authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get the results of a Observation `variables` search request
     - GET /search/variables/{searchResultsDbId}

     - :
       - type: http
       - name: AuthorizationToken
     - examples: [{contentType=application/json, example={
  "result" : {
    "data" : [ {
      "commonCropName" : "Maize",
      "documentationURL" : "https://wiki.brapi.org/documentation.html",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "method" : {
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "methodClass" : "Measurement",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "description" : "A measuring tape was used",
        "formula" : "a^2 + b^2 = c^2",
        "methodName" : "Measuring Tape",
        "methodDbId" : "0adb2764",
        "ontologyReference" : {
          "ontologyDbId" : "6b071868",
          "ontologyName" : "The Crop Ontology",
          "documentationLinks" : [ {
            "type" : "OBO",
            "URL" : "http://purl.obolibrary.org/obo/ro.owl"
          }, {
            "type" : "OBO",
            "URL" : "http://purl.obolibrary.org/obo/ro.owl"
          } ],
          "version" : "7.2.3"
        },
        "bibliographicalReference" : "Smith, 1893, Really Cool Paper, Popular Journal"
      },
      "defaultValue" : "2.0",
      "scientist" : "Dr. Bob Robertson",
      "synonyms" : [ "Maize Height", "Stalk Height", "Corn Height" ],
      "observationVariableName" : "Variable Name",
      "scale" : {
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "decimalPlaces" : 2,
        "dataType" : "Numerical",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "scaleDbId" : "af730171",
        "scaleName" : "Meters",
        "validValues" : {
          "min" : 2,
          "max" : 9999,
          "categories" : [ {
            "label" : "low",
            "value" : "0"
          }, {
            "label" : "medium",
            "value" : "5"
          }, {
            "label" : "high",
            "value" : "10"
          } ]
        }
      },
      "language" : "en",
      "contextOfUse" : [ "Trial evaluation", "Nursery evaluation" ],
      "submissionTimestamp" : "2000-01-23T04:56:07.000+00:00",
      "institution" : "The BrAPI Institute",
      "growthStage" : "flowering",
      "observationVariableDbId" : "b9b7edd1",
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "trait" : {
        "traitName" : "Height",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "synonyms" : [ "Height", "Plant Height", "Stalk Height", "Canopy Height" ],
        "traitDbId" : "9b2e34f5",
        "alternativeAbbreviations" : [ "H", "PH", "H1" ],
        "mainAbbreviation" : "PH",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "attribute" : "height",
        "traitDescription" : "The height of the plant",
        "entity" : "Stalk",
        "status" : "recommended",
        "traitClass" : "phenological"
      },
      "status" : "recommended"
    }, {
      "commonCropName" : "Maize",
      "documentationURL" : "https://wiki.brapi.org/documentation.html",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "method" : {
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "methodClass" : "Measurement",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "description" : "A measuring tape was used",
        "formula" : "a^2 + b^2 = c^2",
        "methodName" : "Measuring Tape",
        "methodDbId" : "0adb2764",
        "ontologyReference" : {
          "ontologyDbId" : "6b071868",
          "ontologyName" : "The Crop Ontology",
          "documentationLinks" : [ {
            "type" : "OBO",
            "URL" : "http://purl.obolibrary.org/obo/ro.owl"
          }, {
            "type" : "OBO",
            "URL" : "http://purl.obolibrary.org/obo/ro.owl"
          } ],
          "version" : "7.2.3"
        },
        "bibliographicalReference" : "Smith, 1893, Really Cool Paper, Popular Journal"
      },
      "defaultValue" : "2.0",
      "scientist" : "Dr. Bob Robertson",
      "synonyms" : [ "Maize Height", "Stalk Height", "Corn Height" ],
      "observationVariableName" : "Variable Name",
      "scale" : {
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "decimalPlaces" : 2,
        "dataType" : "Numerical",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "scaleDbId" : "af730171",
        "scaleName" : "Meters",
        "validValues" : {
          "min" : 2,
          "max" : 9999,
          "categories" : [ {
            "label" : "low",
            "value" : "0"
          }, {
            "label" : "medium",
            "value" : "5"
          }, {
            "label" : "high",
            "value" : "10"
          } ]
        }
      },
      "language" : "en",
      "contextOfUse" : [ "Trial evaluation", "Nursery evaluation" ],
      "submissionTimestamp" : "2000-01-23T04:56:07.000+00:00",
      "institution" : "The BrAPI Institute",
      "growthStage" : "flowering",
      "observationVariableDbId" : "b9b7edd1",
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "trait" : {
        "traitName" : "Height",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "synonyms" : [ "Height", "Plant Height", "Stalk Height", "Canopy Height" ],
        "traitDbId" : "9b2e34f5",
        "alternativeAbbreviations" : [ "H", "PH", "H1" ],
        "mainAbbreviation" : "PH",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "attribute" : "height",
        "traitDescription" : "The height of the plant",
        "entity" : "Stalk",
        "status" : "recommended",
        "traitClass" : "phenological"
      },
      "status" : "recommended"
    } ]
  },
  "metadata" : {
    "pagination" : {
      "totalPages" : 1,
      "pageSize" : 1000,
      "currentPage" : 0,
      "totalCount" : 10
    },
    "datafiles" : [ {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    }, {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    } ],
    "status" : [ {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    }, {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    } ]
  },
  "@context" : [ "https://brapi.org/jsonld/context/metadata.jsonld" ]
}}]
     - parameter searchResultsDbId: (path) Unique identifier which references the search results 
     - parameter page: (query) Used to request a specific page of data to be returned.  The page indexing starts at 0 (the first page is &#x27;page&#x27;&#x3D; 0). Default is &#x60;0&#x60;. (optional)
     - parameter pageSize: (query) The size of the pages to be returned. Default is &#x60;1000&#x60;. (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)

     - returns: RequestBuilder<ObservationVariableListResponse> 
     */
    open class func searchVariablesSearchResultsDbIdGetWithRequestBuilder(searchResultsDbId: String, page: Int? = nil, pageSize: Int? = nil, authorization: String? = nil) -> RequestBuilder<ObservationVariableListResponse> {
        var path = "/search/variables/{searchResultsDbId}"
        let searchResultsDbIdPreEscape = "\(searchResultsDbId)"
        let searchResultsDbIdPostEscape = searchResultsDbIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{searchResultsDbId}", with: searchResultsDbIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "page": page?.encodeToJSON(), 
                        "pageSize": pageSize?.encodeToJSON()
        ])
        let nillableHeaders: [String: Any?] = [
                        "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ObservationVariableListResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     Get the Observation Variables

     - parameter observationVariableDbId: (query) Variable&#x27;s unique ID (optional)
     - parameter traitClass: (query) Variable&#x27;s trait class (phenological, physiological, morphological, etc.) (optional)
     - parameter studyDbId: (query) The unique ID of a studies to filter on (optional)
     - parameter externalReferenceID: (query) An external reference ID. Could be a simple string or a URI. (use with &#x60;externalReferenceSource&#x60; parameter) (optional)
     - parameter externalReferenceSource: (query) An identifier for the source system or database of an external reference (use with &#x60;externalReferenceID&#x60; parameter) (optional)
     - parameter page: (query) Used to request a specific page of data to be returned.  The page indexing starts at 0 (the first page is &#x27;page&#x27;&#x3D; 0). Default is &#x60;0&#x60;. (optional)
     - parameter pageSize: (query) The size of the pages to be returned. Default is &#x60;1000&#x60;. (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func variablesGet(observationVariableDbId: String? = nil, traitClass: String? = nil, studyDbId: String? = nil, externalReferenceID: String? = nil, externalReferenceSource: String? = nil, page: Int? = nil, pageSize: Int? = nil, authorization: String? = nil, completion: @escaping ((_ data: ObservationVariableListResponse?,_ error: Error?) -> Void)) {
        variablesGetWithRequestBuilder(observationVariableDbId: observationVariableDbId, traitClass: traitClass, studyDbId: studyDbId, externalReferenceID: externalReferenceID, externalReferenceSource: externalReferenceSource, page: page, pageSize: pageSize, authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get the Observation Variables
     - GET /variables

     - :
       - type: http
       - name: AuthorizationToken
     - examples: [{contentType=application/json, example={
  "result" : {
    "data" : [ {
      "commonCropName" : "Maize",
      "documentationURL" : "https://wiki.brapi.org/documentation.html",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "method" : {
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "methodClass" : "Measurement",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "description" : "A measuring tape was used",
        "formula" : "a^2 + b^2 = c^2",
        "methodName" : "Measuring Tape",
        "methodDbId" : "0adb2764",
        "ontologyReference" : {
          "ontologyDbId" : "6b071868",
          "ontologyName" : "The Crop Ontology",
          "documentationLinks" : [ {
            "type" : "OBO",
            "URL" : "http://purl.obolibrary.org/obo/ro.owl"
          }, {
            "type" : "OBO",
            "URL" : "http://purl.obolibrary.org/obo/ro.owl"
          } ],
          "version" : "7.2.3"
        },
        "bibliographicalReference" : "Smith, 1893, Really Cool Paper, Popular Journal"
      },
      "defaultValue" : "2.0",
      "scientist" : "Dr. Bob Robertson",
      "synonyms" : [ "Maize Height", "Stalk Height", "Corn Height" ],
      "observationVariableName" : "Variable Name",
      "scale" : {
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "decimalPlaces" : 2,
        "dataType" : "Numerical",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "scaleDbId" : "af730171",
        "scaleName" : "Meters",
        "validValues" : {
          "min" : 2,
          "max" : 9999,
          "categories" : [ {
            "label" : "low",
            "value" : "0"
          }, {
            "label" : "medium",
            "value" : "5"
          }, {
            "label" : "high",
            "value" : "10"
          } ]
        }
      },
      "language" : "en",
      "contextOfUse" : [ "Trial evaluation", "Nursery evaluation" ],
      "submissionTimestamp" : "2000-01-23T04:56:07.000+00:00",
      "institution" : "The BrAPI Institute",
      "growthStage" : "flowering",
      "observationVariableDbId" : "b9b7edd1",
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "trait" : {
        "traitName" : "Height",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "synonyms" : [ "Height", "Plant Height", "Stalk Height", "Canopy Height" ],
        "traitDbId" : "9b2e34f5",
        "alternativeAbbreviations" : [ "H", "PH", "H1" ],
        "mainAbbreviation" : "PH",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "attribute" : "height",
        "traitDescription" : "The height of the plant",
        "entity" : "Stalk",
        "status" : "recommended",
        "traitClass" : "phenological"
      },
      "status" : "recommended"
    }, {
      "commonCropName" : "Maize",
      "documentationURL" : "https://wiki.brapi.org/documentation.html",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "method" : {
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "methodClass" : "Measurement",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "description" : "A measuring tape was used",
        "formula" : "a^2 + b^2 = c^2",
        "methodName" : "Measuring Tape",
        "methodDbId" : "0adb2764",
        "ontologyReference" : {
          "ontologyDbId" : "6b071868",
          "ontologyName" : "The Crop Ontology",
          "documentationLinks" : [ {
            "type" : "OBO",
            "URL" : "http://purl.obolibrary.org/obo/ro.owl"
          }, {
            "type" : "OBO",
            "URL" : "http://purl.obolibrary.org/obo/ro.owl"
          } ],
          "version" : "7.2.3"
        },
        "bibliographicalReference" : "Smith, 1893, Really Cool Paper, Popular Journal"
      },
      "defaultValue" : "2.0",
      "scientist" : "Dr. Bob Robertson",
      "synonyms" : [ "Maize Height", "Stalk Height", "Corn Height" ],
      "observationVariableName" : "Variable Name",
      "scale" : {
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "decimalPlaces" : 2,
        "dataType" : "Numerical",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "scaleDbId" : "af730171",
        "scaleName" : "Meters",
        "validValues" : {
          "min" : 2,
          "max" : 9999,
          "categories" : [ {
            "label" : "low",
            "value" : "0"
          }, {
            "label" : "medium",
            "value" : "5"
          }, {
            "label" : "high",
            "value" : "10"
          } ]
        }
      },
      "language" : "en",
      "contextOfUse" : [ "Trial evaluation", "Nursery evaluation" ],
      "submissionTimestamp" : "2000-01-23T04:56:07.000+00:00",
      "institution" : "The BrAPI Institute",
      "growthStage" : "flowering",
      "observationVariableDbId" : "b9b7edd1",
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "trait" : {
        "traitName" : "Height",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "synonyms" : [ "Height", "Plant Height", "Stalk Height", "Canopy Height" ],
        "traitDbId" : "9b2e34f5",
        "alternativeAbbreviations" : [ "H", "PH", "H1" ],
        "mainAbbreviation" : "PH",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "attribute" : "height",
        "traitDescription" : "The height of the plant",
        "entity" : "Stalk",
        "status" : "recommended",
        "traitClass" : "phenological"
      },
      "status" : "recommended"
    } ]
  },
  "metadata" : {
    "pagination" : {
      "totalPages" : 1,
      "pageSize" : 1000,
      "currentPage" : 0,
      "totalCount" : 10
    },
    "datafiles" : [ {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    }, {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    } ],
    "status" : [ {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    }, {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    } ]
  },
  "@context" : [ "https://brapi.org/jsonld/context/metadata.jsonld" ]
}}]
     - parameter observationVariableDbId: (query) Variable&#x27;s unique ID (optional)
     - parameter traitClass: (query) Variable&#x27;s trait class (phenological, physiological, morphological, etc.) (optional)
     - parameter studyDbId: (query) The unique ID of a studies to filter on (optional)
     - parameter externalReferenceID: (query) An external reference ID. Could be a simple string or a URI. (use with &#x60;externalReferenceSource&#x60; parameter) (optional)
     - parameter externalReferenceSource: (query) An identifier for the source system or database of an external reference (use with &#x60;externalReferenceID&#x60; parameter) (optional)
     - parameter page: (query) Used to request a specific page of data to be returned.  The page indexing starts at 0 (the first page is &#x27;page&#x27;&#x3D; 0). Default is &#x60;0&#x60;. (optional)
     - parameter pageSize: (query) The size of the pages to be returned. Default is &#x60;1000&#x60;. (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)

     - returns: RequestBuilder<ObservationVariableListResponse> 
     */
    open class func variablesGetWithRequestBuilder(observationVariableDbId: String? = nil, traitClass: String? = nil, studyDbId: String? = nil, externalReferenceID: String? = nil, externalReferenceSource: String? = nil, page: Int? = nil, pageSize: Int? = nil, authorization: String? = nil) -> RequestBuilder<ObservationVariableListResponse> {
        let path = "/variables"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "observationVariableDbId": observationVariableDbId, 
                        "traitClass": traitClass, 
                        "studyDbId": studyDbId, 
                        "externalReferenceID": externalReferenceID, 
                        "externalReferenceSource": externalReferenceSource, 
                        "page": page?.encodeToJSON(), 
                        "pageSize": pageSize?.encodeToJSON()
        ])
        let nillableHeaders: [String: Any?] = [
                        "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ObservationVariableListResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     Get the details for a specific Observation Variable

     - parameter observationVariableDbId: (path) string id of the variable 
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func variablesObservationVariableDbIdGet(observationVariableDbId: String, authorization: String? = nil, completion: @escaping ((_ data: ObservationVariableSingleResponse?,_ error: Error?) -> Void)) {
        variablesObservationVariableDbIdGetWithRequestBuilder(observationVariableDbId: observationVariableDbId, authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get the details for a specific Observation Variable
     - GET /variables/{observationVariableDbId}

     - :
       - type: http
       - name: AuthorizationToken
     - examples: [{contentType=application/json, example={
  "result" : {
    "commonCropName" : "Maize",
    "documentationURL" : "https://wiki.brapi.org/documentation.html",
    "externalReferences" : [ {
      "referenceID" : "doi:10.155454/12341234",
      "referenceSource" : "DOI"
    }, {
      "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
      "referenceSource" : "OBO Library"
    }, {
      "referenceID" : "75a50e76",
      "referenceSource" : "Remote Data Collection Upload Tool"
    } ],
    "method" : {
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "methodClass" : "Measurement",
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "description" : "A measuring tape was used",
      "formula" : "a^2 + b^2 = c^2",
      "methodName" : "Measuring Tape",
      "methodDbId" : "0adb2764",
      "ontologyReference" : {
        "ontologyDbId" : "6b071868",
        "ontologyName" : "The Crop Ontology",
        "documentationLinks" : [ {
          "type" : "OBO",
          "URL" : "http://purl.obolibrary.org/obo/ro.owl"
        }, {
          "type" : "OBO",
          "URL" : "http://purl.obolibrary.org/obo/ro.owl"
        } ],
        "version" : "7.2.3"
      },
      "bibliographicalReference" : "Smith, 1893, Really Cool Paper, Popular Journal"
    },
    "defaultValue" : "2.0",
    "scientist" : "Dr. Bob Robertson",
    "synonyms" : [ "Maize Height", "Stalk Height", "Corn Height" ],
    "observationVariableName" : "Variable Name",
    "scale" : {
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "decimalPlaces" : 2,
      "dataType" : "Numerical",
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "scaleDbId" : "af730171",
      "scaleName" : "Meters",
      "validValues" : {
        "min" : 2,
        "max" : 9999,
        "categories" : [ {
          "label" : "low",
          "value" : "0"
        }, {
          "label" : "medium",
          "value" : "5"
        }, {
          "label" : "high",
          "value" : "10"
        } ]
      }
    },
    "language" : "en",
    "contextOfUse" : [ "Trial evaluation", "Nursery evaluation" ],
    "submissionTimestamp" : "2000-01-23T04:56:07.000+00:00",
    "institution" : "The BrAPI Institute",
    "growthStage" : "flowering",
    "observationVariableDbId" : "b9b7edd1",
    "additionalInfo" : {
      "key" : "additionalInfo"
    },
    "trait" : {
      "traitName" : "Height",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "synonyms" : [ "Height", "Plant Height", "Stalk Height", "Canopy Height" ],
      "traitDbId" : "9b2e34f5",
      "alternativeAbbreviations" : [ "H", "PH", "H1" ],
      "mainAbbreviation" : "PH",
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "attribute" : "height",
      "traitDescription" : "The height of the plant",
      "entity" : "Stalk",
      "status" : "recommended",
      "traitClass" : "phenological"
    },
    "status" : "recommended"
  },
  "metadata" : {
    "pagination" : {
      "totalPages" : 1,
      "pageSize" : 1000,
      "currentPage" : 0,
      "totalCount" : 10
    },
    "datafiles" : [ {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    }, {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    } ],
    "status" : [ {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    }, {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    } ]
  },
  "@context" : [ "https://brapi.org/jsonld/context/metadata.jsonld" ]
}}]
     - parameter observationVariableDbId: (path) string id of the variable 
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)

     - returns: RequestBuilder<ObservationVariableSingleResponse> 
     */
    open class func variablesObservationVariableDbIdGetWithRequestBuilder(observationVariableDbId: String, authorization: String? = nil) -> RequestBuilder<ObservationVariableSingleResponse> {
        var path = "/variables/{observationVariableDbId}"
        let observationVariableDbIdPreEscape = "\(observationVariableDbId)"
        let observationVariableDbIdPostEscape = observationVariableDbIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{observationVariableDbId}", with: observationVariableDbIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
                        "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ObservationVariableSingleResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     Update an existing Observation Variable

     - parameter observationVariableDbId: (path) string id of the variable 
     - parameter body: (body)  (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func variablesObservationVariableDbIdPut(observationVariableDbId: String, body: ObservationVariableNewRequest? = nil, authorization: String? = nil, completion: @escaping ((_ data: ObservationVariableSingleResponse?,_ error: Error?) -> Void)) {
        variablesObservationVariableDbIdPutWithRequestBuilder(observationVariableDbId: observationVariableDbId, body: body, authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Update an existing Observation Variable
     - PUT /variables/{observationVariableDbId}

     - :
       - type: http
       - name: AuthorizationToken
     - examples: [{contentType=application/json, example={
  "result" : {
    "commonCropName" : "Maize",
    "documentationURL" : "https://wiki.brapi.org/documentation.html",
    "externalReferences" : [ {
      "referenceID" : "doi:10.155454/12341234",
      "referenceSource" : "DOI"
    }, {
      "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
      "referenceSource" : "OBO Library"
    }, {
      "referenceID" : "75a50e76",
      "referenceSource" : "Remote Data Collection Upload Tool"
    } ],
    "method" : {
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "methodClass" : "Measurement",
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "description" : "A measuring tape was used",
      "formula" : "a^2 + b^2 = c^2",
      "methodName" : "Measuring Tape",
      "methodDbId" : "0adb2764",
      "ontologyReference" : {
        "ontologyDbId" : "6b071868",
        "ontologyName" : "The Crop Ontology",
        "documentationLinks" : [ {
          "type" : "OBO",
          "URL" : "http://purl.obolibrary.org/obo/ro.owl"
        }, {
          "type" : "OBO",
          "URL" : "http://purl.obolibrary.org/obo/ro.owl"
        } ],
        "version" : "7.2.3"
      },
      "bibliographicalReference" : "Smith, 1893, Really Cool Paper, Popular Journal"
    },
    "defaultValue" : "2.0",
    "scientist" : "Dr. Bob Robertson",
    "synonyms" : [ "Maize Height", "Stalk Height", "Corn Height" ],
    "observationVariableName" : "Variable Name",
    "scale" : {
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "decimalPlaces" : 2,
      "dataType" : "Numerical",
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "scaleDbId" : "af730171",
      "scaleName" : "Meters",
      "validValues" : {
        "min" : 2,
        "max" : 9999,
        "categories" : [ {
          "label" : "low",
          "value" : "0"
        }, {
          "label" : "medium",
          "value" : "5"
        }, {
          "label" : "high",
          "value" : "10"
        } ]
      }
    },
    "language" : "en",
    "contextOfUse" : [ "Trial evaluation", "Nursery evaluation" ],
    "submissionTimestamp" : "2000-01-23T04:56:07.000+00:00",
    "institution" : "The BrAPI Institute",
    "growthStage" : "flowering",
    "observationVariableDbId" : "b9b7edd1",
    "additionalInfo" : {
      "key" : "additionalInfo"
    },
    "trait" : {
      "traitName" : "Height",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "synonyms" : [ "Height", "Plant Height", "Stalk Height", "Canopy Height" ],
      "traitDbId" : "9b2e34f5",
      "alternativeAbbreviations" : [ "H", "PH", "H1" ],
      "mainAbbreviation" : "PH",
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "attribute" : "height",
      "traitDescription" : "The height of the plant",
      "entity" : "Stalk",
      "status" : "recommended",
      "traitClass" : "phenological"
    },
    "status" : "recommended"
  },
  "metadata" : {
    "pagination" : {
      "totalPages" : 1,
      "pageSize" : 1000,
      "currentPage" : 0,
      "totalCount" : 10
    },
    "datafiles" : [ {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    }, {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    } ],
    "status" : [ {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    }, {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    } ]
  },
  "@context" : [ "https://brapi.org/jsonld/context/metadata.jsonld" ]
}}]
     - parameter observationVariableDbId: (path) string id of the variable 
     - parameter body: (body)  (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)

     - returns: RequestBuilder<ObservationVariableSingleResponse> 
     */
    open class func variablesObservationVariableDbIdPutWithRequestBuilder(observationVariableDbId: String, body: ObservationVariableNewRequest? = nil, authorization: String? = nil) -> RequestBuilder<ObservationVariableSingleResponse> {
        var path = "/variables/{observationVariableDbId}"
        let observationVariableDbIdPreEscape = "\(observationVariableDbId)"
        let observationVariableDbIdPostEscape = observationVariableDbIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{observationVariableDbId}", with: observationVariableDbIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
                        "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ObservationVariableSingleResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     Add new Observation Variables

     - parameter body: (body)  (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func variablesPost(body: [ObservationVariableNewRequest]? = nil, authorization: String? = nil, completion: @escaping ((_ data: ObservationVariableListResponse?,_ error: Error?) -> Void)) {
        variablesPostWithRequestBuilder(body: body, authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Add new Observation Variables
     - POST /variables

     - :
       - type: http
       - name: AuthorizationToken
     - examples: [{contentType=application/json, example={
  "result" : {
    "data" : [ {
      "commonCropName" : "Maize",
      "documentationURL" : "https://wiki.brapi.org/documentation.html",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "method" : {
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "methodClass" : "Measurement",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "description" : "A measuring tape was used",
        "formula" : "a^2 + b^2 = c^2",
        "methodName" : "Measuring Tape",
        "methodDbId" : "0adb2764",
        "ontologyReference" : {
          "ontologyDbId" : "6b071868",
          "ontologyName" : "The Crop Ontology",
          "documentationLinks" : [ {
            "type" : "OBO",
            "URL" : "http://purl.obolibrary.org/obo/ro.owl"
          }, {
            "type" : "OBO",
            "URL" : "http://purl.obolibrary.org/obo/ro.owl"
          } ],
          "version" : "7.2.3"
        },
        "bibliographicalReference" : "Smith, 1893, Really Cool Paper, Popular Journal"
      },
      "defaultValue" : "2.0",
      "scientist" : "Dr. Bob Robertson",
      "synonyms" : [ "Maize Height", "Stalk Height", "Corn Height" ],
      "observationVariableName" : "Variable Name",
      "scale" : {
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "decimalPlaces" : 2,
        "dataType" : "Numerical",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "scaleDbId" : "af730171",
        "scaleName" : "Meters",
        "validValues" : {
          "min" : 2,
          "max" : 9999,
          "categories" : [ {
            "label" : "low",
            "value" : "0"
          }, {
            "label" : "medium",
            "value" : "5"
          }, {
            "label" : "high",
            "value" : "10"
          } ]
        }
      },
      "language" : "en",
      "contextOfUse" : [ "Trial evaluation", "Nursery evaluation" ],
      "submissionTimestamp" : "2000-01-23T04:56:07.000+00:00",
      "institution" : "The BrAPI Institute",
      "growthStage" : "flowering",
      "observationVariableDbId" : "b9b7edd1",
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "trait" : {
        "traitName" : "Height",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "synonyms" : [ "Height", "Plant Height", "Stalk Height", "Canopy Height" ],
        "traitDbId" : "9b2e34f5",
        "alternativeAbbreviations" : [ "H", "PH", "H1" ],
        "mainAbbreviation" : "PH",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "attribute" : "height",
        "traitDescription" : "The height of the plant",
        "entity" : "Stalk",
        "status" : "recommended",
        "traitClass" : "phenological"
      },
      "status" : "recommended"
    }, {
      "commonCropName" : "Maize",
      "documentationURL" : "https://wiki.brapi.org/documentation.html",
      "externalReferences" : [ {
        "referenceID" : "doi:10.155454/12341234",
        "referenceSource" : "DOI"
      }, {
        "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
        "referenceSource" : "OBO Library"
      }, {
        "referenceID" : "75a50e76",
        "referenceSource" : "Remote Data Collection Upload Tool"
      } ],
      "method" : {
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "methodClass" : "Measurement",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "description" : "A measuring tape was used",
        "formula" : "a^2 + b^2 = c^2",
        "methodName" : "Measuring Tape",
        "methodDbId" : "0adb2764",
        "ontologyReference" : {
          "ontologyDbId" : "6b071868",
          "ontologyName" : "The Crop Ontology",
          "documentationLinks" : [ {
            "type" : "OBO",
            "URL" : "http://purl.obolibrary.org/obo/ro.owl"
          }, {
            "type" : "OBO",
            "URL" : "http://purl.obolibrary.org/obo/ro.owl"
          } ],
          "version" : "7.2.3"
        },
        "bibliographicalReference" : "Smith, 1893, Really Cool Paper, Popular Journal"
      },
      "defaultValue" : "2.0",
      "scientist" : "Dr. Bob Robertson",
      "synonyms" : [ "Maize Height", "Stalk Height", "Corn Height" ],
      "observationVariableName" : "Variable Name",
      "scale" : {
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "decimalPlaces" : 2,
        "dataType" : "Numerical",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "scaleDbId" : "af730171",
        "scaleName" : "Meters",
        "validValues" : {
          "min" : 2,
          "max" : 9999,
          "categories" : [ {
            "label" : "low",
            "value" : "0"
          }, {
            "label" : "medium",
            "value" : "5"
          }, {
            "label" : "high",
            "value" : "10"
          } ]
        }
      },
      "language" : "en",
      "contextOfUse" : [ "Trial evaluation", "Nursery evaluation" ],
      "submissionTimestamp" : "2000-01-23T04:56:07.000+00:00",
      "institution" : "The BrAPI Institute",
      "growthStage" : "flowering",
      "observationVariableDbId" : "b9b7edd1",
      "additionalInfo" : {
        "key" : "additionalInfo"
      },
      "trait" : {
        "traitName" : "Height",
        "externalReferences" : [ {
          "referenceID" : "doi:10.155454/12341234",
          "referenceSource" : "DOI"
        }, {
          "referenceID" : "http://purl.obolibrary.org/obo/ro.owl",
          "referenceSource" : "OBO Library"
        }, {
          "referenceID" : "75a50e76",
          "referenceSource" : "Remote Data Collection Upload Tool"
        } ],
        "synonyms" : [ "Height", "Plant Height", "Stalk Height", "Canopy Height" ],
        "traitDbId" : "9b2e34f5",
        "alternativeAbbreviations" : [ "H", "PH", "H1" ],
        "mainAbbreviation" : "PH",
        "additionalInfo" : {
          "key" : "additionalInfo"
        },
        "attribute" : "height",
        "traitDescription" : "The height of the plant",
        "entity" : "Stalk",
        "status" : "recommended",
        "traitClass" : "phenological"
      },
      "status" : "recommended"
    } ]
  },
  "metadata" : {
    "pagination" : {
      "totalPages" : 1,
      "pageSize" : 1000,
      "currentPage" : 0,
      "totalCount" : 10
    },
    "datafiles" : [ {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    }, {
      "fileDescription" : "This is an Excel data file",
      "fileName" : "datafile.xlsx",
      "fileSize" : 4398,
      "fileMD5Hash" : "c2365e900c81a89cf74d83dab60df146",
      "fileURL" : "https://wiki.brapi.org/examples/datafile.xlsx",
      "fileType" : "application/vnd.ms-excel"
    } ],
    "status" : [ {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    }, {
      "messageType" : "INFO",
      "message" : "Request accepted, response successful"
    } ]
  },
  "@context" : [ "https://brapi.org/jsonld/context/metadata.jsonld" ]
}}]
     - parameter body: (body)  (optional)
     - parameter authorization: (header) HTTP HEADER - Token used for Authorization   &lt;strong&gt; Bearer {token_string} &lt;/strong&gt; (optional)

     - returns: RequestBuilder<ObservationVariableListResponse> 
     */
    open class func variablesPostWithRequestBuilder(body: [ObservationVariableNewRequest]? = nil, authorization: String? = nil) -> RequestBuilder<ObservationVariableListResponse> {
        let path = "/variables"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
                        "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ObservationVariableListResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
}
