//
// BasePagination.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BasePagination: Codable {

    /** The number of data elements returned, aka the size of the current page. If the requested page does not have enough elements to fill a page at the requested page size, this field should indicate the actual number of elements returned. */
    public var pageSize: Int
    /** The total number of elements that are available on the server and match the requested query parameters. */
    public var totalCount: Int?
    /** The total number of pages of elements available on the server. This should be calculated with the following formula.   totalPages &#x3D; CEILING( totalCount / requested_page_size) */
    public var totalPages: Int?

    public init(pageSize: Int, totalCount: Int? = nil, totalPages: Int? = nil) {
        self.pageSize = pageSize
        self.totalCount = totalCount
        self.totalPages = totalPages
    }


}
