//
// GeoJSONSearchArea.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A GeoJSON Polygon which describes an area to search for other GeoJSON objects. All contained Points and intersecting Polygons should be returned as search results.   All coordinates are decimal values on the WGS84 geographic coordinate reference system. */

public struct GeoJSONSearchArea: Codable {

    /** A geometry as defined by GeoJSON (RFC 7946). In this context, only Point or Polygon geometry are allowed. */
    public var geometry: OneOfGeoJSONSearchAreaGeometry?
    /** The literal string \&quot;Feature\&quot; */
    public var type: String?

    public init(geometry: OneOfGeoJSONSearchAreaGeometry? = nil, type: String? = nil) {
        self.geometry = geometry
        self.type = type
    }


}
