//
// ObservationVariableScaleValidValuesCategories.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ObservationVariableScaleValidValuesCategories: Codable {

    /** A text label for a category */
    public var label: String?
    /** The actual value for a category */
    public var value: String?

    public init(label: String? = nil, value: String? = nil) {
        self.label = label
        self.value = value
    }


}
