//
// SearchRequestParametersCommonCropNames.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchRequestParametersCommonCropNames: Codable {

    /** Common name for the crop which this program is for */
    public var commonCropNames: [String]?

    public init(commonCropNames: [String]? = nil) {
        self.commonCropNames = commonCropNames
    }


}
