//
// SeasonListResponseResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SeasonListResponseResult: Codable {

    public var data: [Season]

    public init(data: [Season]) {
        self.data = data
    }


}
