//
// StudyGrowthFacility.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Short description of the facility in which the study was carried out. */

public struct StudyGrowthFacility: Codable {

    /** MIAPPE V1.1 (DM-27) Type of growth facility - Type of growth facility in which the study was carried out, in the form of an accession number from the Crop Ontology. */
    public var PUI: String?
    /** MIAPPE V1.1 (DM-26) Description of growth facility - Short description of the facility in which the study was carried out. */
    public var _description: String?

    public init(PUI: String? = nil, _description: String? = nil) {
        self.PUI = PUI
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case PUI
        case _description = "description"
    }

}
