//
// TraitListResponseResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TraitListResponseResult: Codable {

    public var data: [Trait]

    public init(data: [Trait]) {
        self.data = data
    }


}
